import {lessons,n,choice} from './lessons.mjs';
const b3=lessons.find(l=>l.id==='B03');
b3.complete=true;
b3.duration='2 sessões de 60 minutos';
b3.extra=`
<nav class="note" aria-label="Roteiro da aula"><h2>Organiza as duas sessões</h2><p>Na primeira, trabalha funções, tabelas, gráficos e retas. Na segunda, compara curvas, aprende a ler potências e logaritmos e resolve os exercícios. Mantém o papel ao lado: desenhar três pontos ajuda mais do que decorar uma definição.</p><ol><li><a href="#funcao">O que torna uma regra numa função</a></li><li><a href="#grafico">Da tabela ao gráfico</a></li><li><a href="#reta">Declive, origem e zeros</a></li><li><a href="#potencias">Potências e raízes</a></li><li><a href="#crescimento">Três tipos de crescimento</a></li><li><a href="#logaritmos">Logaritmos e composição</a></li></ol></nav>
<section id="funcao"><h2>1. Uma entrada, uma saída definida</h2><p>Uma função associa a <strong>cada entrada permitida exatamente uma saída</strong>. A notação f(x) lê-se “f de x”. Em f(x) = 2x + 1, f é o nome da função, x é a entrada e 2x + 1 é a regra. Para x = 3: f(3) = 2 × 3 + 1 = 7. Não estamos a multiplicar f por x.</p><p>Em front-end, uma função que converte uma largura em tamanho de letra é uma analogia útil. Na função matemática aqui estudada, a mesma entrada tem sempre a mesma saída; não depende de estado escondido, hora atual ou chamadas aleatórias. Funções de programação podem ter esses comportamentos, por isso a analogia tem limites.</p><p>O <strong>domínio</strong> reúne as entradas permitidas. Se x conta imagens, pode ser {0,1,2,3,…}, o conjunto dos inteiros não negativos. Se x mede tempo, pode ser qualquer real não negativo. Os símbolos { } delimitam um conjunto; as reticências indicam continuação. Escrever x ≥ 0 significa “x maior ou igual a zero”.</p><p>O <strong>contradomínio</strong> é o conjunto de saídas declarado na definição. A <strong>imagem</strong> é o conjunto das saídas efetivamente obtidas. Se o domínio é {0,1,2}, o contradomínio é o conjunto dos reais e f(x)=2x+1, a imagem é {1,3,5}. O número 2 pertence ao contradomínio mas não à imagem deste exemplo.</p><p>Duas entradas podem dar a mesma saída: em f(x)=x², −2 e 2 dão 4. Continua a ser função. O que não pode acontecer é a mesma entrada ter duas saídas diferentes na mesma definição.</p><h3>Quando uma entrada não serve</h3><p>Na regra g(x)=1/(x−2), x=2 faria o denominador zero, por isso está excluído. Na regra h(x)=√x, quando trabalhamos com números reais, x não pode ser negativo. A raiz quadrada √x é o número não negativo cujo quadrado é x. Já num modelo de custo, uma entrada pode ser matematicamente calculável mas inválida no contexto: −3 pedidos não é uma contagem admissível.</p></section>
<section id="grafico"><h2>2. Representar a mesma relação de três maneiras</h2><p>Considera f(x)=20x+100, com x em imagens e f(x) em milissegundos. Para x=0, o valor é 100. Para x=1, é 120. Para x=2, é 140. A tabela lista as entradas e saídas; o gráfico coloca cada par como um ponto.</p><table><caption>Modelo simplificado de latência</caption><thead><tr><th scope="col">Imagens x</th><th scope="col">Latência f(x), ms</th></tr></thead><tbody><tr><td>0</td><td>100</td></tr><tr><td>1</td><td>120</td></tr><tr><td>2</td><td>140</td></tr><tr><td>3</td><td>160</td></tr></tbody></table><figure><svg viewBox="0 0 500 260" role="img" aria-label="Gráfico de f(x)=20x+100: pontos (0,100), (1,120), (2,140), (3,160). Eixo horizontal em imagens e vertical de zero a duzentos milissegundos."><path d="M65 25V210H435" fill="none" stroke="#172323"/><path d="M65 120L365 66" stroke="#4265d6" stroke-width="3"/><g fill="#4265d6"><circle cx="65" cy="120" r="5"/><circle cx="165" cy="102" r="5"/><circle cx="265" cy="84" r="5"/><circle cx="365" cy="66" r="5"/></g><g fill="#172323" font-size="14"><text x="38" y="214">0</text><text x="25" y="124">100</text><text x="25" y="34">200</text><text x="60" y="231">0</text><text x="160" y="231">1</text><text x="260" y="231">2</text><text x="360" y="231">3</text><text x="345" y="252">Imagens</text><text x="70" y="18">Latência (ms)</text></g></svg><figcaption>A linha ajuda a visualizar a tendência do modelo; a contagem de imagens só admite inteiros. Os valores exatos estão na tabela.</figcaption></figure><p>Um ponto (2,140) significa entrada 2 e saída 140. O eixo horizontal recebe a entrada; o vertical recebe a saída. A origem é (0,0). Uma divisão horizontal pode valer 1 imagem e uma vertical 100 ms: não compares comprimentos no papel sem ler as escalas.</p><p>Para ler f(2), começa em 2 no eixo horizontal, sobe até ao ponto ou curva e lê a altura no vertical. Para encontrar a entrada correspondente a 140 ms, faz o caminho inverso. Numa curva, uma mesma altura pode encontrar mais de uma entrada.</p><p>Um gráfico com eixo vertical cortado pode exagerar diferenças visualmente. Confirma limites, unidades e espaçamento dos eixos. Unir pontos é uma escolha: medições isoladas não provam o que acontece entre eles. O nosso segmento representa uma fórmula conhecida, não dados experimentais.</p></section>
<section id="reta"><h2>3. Uma reta tem taxa de variação constante</h2><p>Uma função afim tem forma f(x)=mx+b. Aqui m é o declive: quanto a saída muda quando a entrada aumenta uma unidade. b é o valor para x=0, também chamado ordenada na origem. Em f(x)=20x+100, m=20 ms por imagem e b=100 ms.</p><p>Entre duas entradas distintas x₁ e x₂, a taxa média de variação é [f(x₂)−f(x₁)]/(x₂−x₁). Os índices 1 e 2 apenas identificam a primeira e a segunda entrada. Para 1 e 3 imagens: (160−120)/(3−1)=40/2=20 ms por imagem. A divisão não está definida se as duas entradas forem iguais.</p><p>Se m for positivo, a reta sobe; se for negativo, desce; se for zero, a saída é constante. Por exemplo, saldo(x)=50−5x perde 5 euros por utilização. Entre x=2 e x=4, os saldos são 40 e 30: (30−40)/(4−2)=−10/2=−5 euros por utilização.</p><h3>Encontrar o zero</h3><p>Um zero da função é uma entrada que dá saída zero. Em saldo(x)=50−5x, resolve 50−5x=0: subtrai 50, obtendo −5x=−50; divide por −5: x=10. Após dez utilizações, o saldo é zero. O zero é 10, não o número 0: estamos a pedir a entrada.</p><p>Uma reta pode prever valores fora do contexto útil. Após onze utilizações, o modelo de saldo dá −5 €. Isso só faz sentido se saldo negativo for permitido. E prolongar uma tendência para longe dos dados chama-se extrapolar: uma fórmula ajustada para páginas pequenas pode falhar em páginas enormes.</p></section>
<section id="potencias"><h2>4. Potências e raízes sem confundir operações</h2><p>Em 2³, 2 é a base e 3 é o expoente: 2 × 2 × 2 = 8. Para expoentes inteiros positivos, uma potência é uma multiplicação repetida. x² não é 2x: para x=3, dão 9 e 6. Se a base inteira é negativa, usa parênteses: (−2)²=4 e (−2)³=−8.</p><p>Multiplicar potências com a mesma base soma os expoentes: 2² × 2³ = (2×2)×(2×2×2)=2⁵. Dividir pela mesma base não nula subtrai-os: 2⁵/2²=2³. Uma potência elevada a outra multiplica expoentes: (2²)³=2⁶. Estas regras não autorizam somar expoentes numa adição: 2²+2³=4+8=12, não 2⁵.</p><p>Para uma base a não nula, a⁰=1. Um expoente negativo indica inverso: 2⁻³=1/2³=1/8=0,125. Uma raiz quadrada faz a operação inversa do quadrado com saída não negativa: √9=3. Mas resolver x²=9 dá x=3 ou x=−3, pois ambos têm quadrado 9. Distingue a função raiz da equação.</p></section>
<section id="crescimento"><h2>5. Linear, quadrático e exponencial</h2><p>Compara, para x=0,1,2,3,4, as saídas de 2x, x² e 2ˣ. A primeira dá 0,2,4,6,8; a segunda 0,1,4,9,16; a terceira 1,2,4,8,16. Coincidir nalguns pontos não significa ser a mesma função.</p><p>Na linear 2x, somar 1 à entrada soma sempre 2 à saída. Na quadrática x², as diferenças entre saídas são 1,3,5,7: a taxa média muda. Na exponencial 2ˣ, somar 1 à entrada multiplica a saída por 2. Uma diferença constante sugere relação afim; um fator constante sugere relação exponencial, no modelo considerado.</p><p>O número de comparações entre pares pode crescer aproximadamente como o quadrado da quantidade de itens; duplicar a entrada quadruplica x². Um valor que aumenta 10% por etapa segue V(t)=V₀×1,1ᵗ: V₀ é o inicial e t conta etapas. De 100 passa a 110 e depois a 121, não a 120, porque a segunda percentagem incide em 110.</p></section>
<section id="logaritmos"><h2>6. Perguntar pelo expoente e encadear funções</h2><p>log₂(8)=3 significa “a que expoente elevamos 2 para obter 8?”. Como 2³=8, a resposta é 3. Em geral, logₐ(y)=x equivale a aˣ=y, com base a positiva e diferente de 1 e argumento y positivo. Não precisamos ainda de calcular logaritmos arbitrários: começa por potências conhecidas.</p><p>Se uma quantidade duplica em cada etapa e passa de 5 para 40, tens 5×2ᵗ=40. Divide ambos os membros por 5: 2ᵗ=8. Portanto t=3 etapas. O logaritmo ajuda a desfazer uma relação exponencial. Não é dividir 8 por 2.</p><p>Uma composição aplica uma função e depois outra. Define f(x)=2x+1 e g(y)=y². Então g(f(2)): primeiro f(2)=5; depois g(5)=25. A ordem contrária dá f(g(2))=f(4)=9. Em JavaScript, g(f(2)) também exprime essa ordem de avaliação.</p><p>Verifica a compatibilidade das entradas: se g só aceitar valores positivos, f(x) precisa de produzir um valor positivo antes de entrar em g. Compor não remove as restrições de domínio. Nas redes neuronais, vais encadear transformações deste modo.</p></section>`;
b3.questions=[
n('Muito fácil · Para f(x)=3x+1, quanto vale f(2)?',7,'Substitui cada x por 2.','f(2)=3×2+1=6+1=7.'),
n('Muito fácil · Quanto vale 2³?',8,'Multiplica três fatores iguais a 2.','2×2×2=8. Não é 2×3.'),
choice('Fácil · Para g(x)=1/(x−2), qual destas entradas está excluída?',['x=0','x=2','x=3'],1,'O denominador não pode ser zero.','Em x=2, x−2=0. As outras entradas dão denominadores −2 e 1, que são permitidos.'),
n('Médio · f(1)=10 e f(4)=22. Qual é a taxa média entre 1 e 4?',4,'Divide a mudança da saída pela mudança da entrada.','(22−10)/(4−1)=12/3=4 unidades de saída por unidade de entrada.'),
n('Médio · Em saldo(x)=50−5x, qual é o zero da função?',10,'Procura a entrada que faz a saída ser zero.','50−5x=0; −5x=−50; x=10. Verificação: 50−5×10=0.'),
n('Difícil · Uma quantidade começa em 5 e duplica por etapa. Após quantas etapas vale 40?',3,'Divide 40 por 5 e procura a potência de 2.','40/5=8; 2³=8; são 3 etapas: 5→10→20→40.'),
n('Desafiante · f(x)=2x+1 e g(y)=y². Qual é a entrada não negativa x para g(f(x))=49?',3,'A raiz de 49 é 7, mas considera também a alternativa −7 e a restrição x≥0.','(2x+1)²=49 dá 2x+1=7 ou −7. A primeira dá x=3; a segunda x=−4, excluído pelo domínio. Verifica g(f(3))=g(7)=49.')
];
b3.task='Desenha a tabela de f(x)=2x+1 para x=0,1,2,3 e marca os pontos (0,1),(1,3),(2,5),(3,7). Explica o declive 2. No papel, resolve x²=16 e compara com √16: a equação tem soluções −4 e 4; a raiz vale 4. Tapa a resposta ao tentar. Por fim explica por que uma reta não descreve todas as funções.';
