import {lessons,n,choice} from './lessons.mjs';
const b5=lessons.find(l=>l.id==='B05');
b5.complete=true;
b5.duration='2 sessões de 60 minutos';
b5.extra=String.raw`
<nav class="note" aria-label="Roteiro da aula"><h2>O resultado que queremos obter</h2><p>No fim, vais executar um script de análise de latências, identificar o Python que o executou e compreender a saída. Primeira sessão: ambiente e ficheiros. Segunda: código, diagnóstico de erros e repetição. Usa o PowerShell no Windows; não precisas de GPU, conta de cloud ou bibliotecas de IA.</p><ol><li><a href="#ferramentas">Distinguir as ferramentas</a></li><li><a href="#instalacao">Confirmar a instalação</a></li><li><a href="#ambiente">Criar o ambiente virtual</a></li><li><a href="#script">Ler e executar o primeiro script</a></li><li><a href="#dependencias">Dependências e Git</a></li><li><a href="#erros">Investigar erros</a></li></ol></nav>
<section id="ferramentas"><h2>1. Editor, terminal e intérprete têm papéis diferentes</h2><p>O editor guarda texto num ficheiro, como ola.py. O terminal recebe comandos para executar programas. O intérprete Python lê as instruções do ficheiro e executa-as. Abrir o ficheiro no editor não o executa, tal como abrir um ficheiro JavaScript não inicia automaticamente um processo Node.</p><p>Se escreveres apenas py no terminal, podes entrar no modo interativo de Python: aparece o prompt &gt;&gt;&gt;. Aí escreves instruções Python, como print(2 + 3). Para voltar ao PowerShell, escreve exit(). Não copies os símbolos &gt;&gt;&gt; para o teu ficheiro. Comandos como py ola.py pertencem ao terminal, não ao código Python.</p><p>O navegador executa o JavaScript deste site; não executa estes ficheiros Python. GitHub Pages disponibiliza o material, mas os laboratórios correm na tua máquina. Mais tarde, uma aplicação web poderá pedir previsões a um serviço Python por HTTP.</p></section>
<section id="instalacao"><h2>2. Confirmar antes de instalar</h2><p>Abre o PowerShell e executa:</p><pre><code>py --version
python --version</code></pre><p>Basta um comando funcional que identifique Python 3 para prosseguires. Se ambos funcionarem, podem apontar para instalações diferentes: não assumas que são equivalentes. Nesta aula usamos py para criar o ambiente e, depois, o caminho explícito do Python desse ambiente.</p><p>Se nenhum funcionar, consulta a <a href="https://docs.python.org/3/using/windows.html">instalação oficial em Windows</a> e obtém Python a partir de <a href="https://www.python.org/downloads/">python.org</a>. Reabre o terminal após a instalação e volta a verificar. A documentação atual descreve o Python Install Manager; uma instalação existente funcional não precisa de ser substituída para esta aula.</p><p>Se abrir a Microsoft Store em vez de mostrar uma versão, pode existir apenas um alias sem um intérprete disponível. Confirma a instalação segundo a documentação e verifica de novo. Não alteres variáveis do sistema ao acaso. Para este laboratório sem dependências externas, não precisas de escolher a versão mais recente só por ser mais recente.</p></section>
<section id="ambiente"><h2>3. Uma pasta e um ambiente por projeto</h2><p>No teu editor, cria uma pasta nova chamada pratica-ia e abre um terminal nessa pasta. Se a pasta já contiver trabalho, reutiliza-a sem apagar nada. Get-Location mostra a pasta atual; Get-ChildItem lista os ficheiros. Estes são comandos PowerShell, não Python.</p><pre><code>Get-Location
Get-ChildItem
py -m venv .venv
./.venv/Scripts/python.exe --version
./.venv/Scripts/python.exe -c "import sys; print(sys.executable)"</code></pre><p>O argumento -m pede ao Python que execute um módulo; venv cria o ambiente e .venv é a pasta de destino. O último comando executa uma pequena instrução passada como texto com -c. sys é um módulo da biblioteca padrão e sys.executable identifica o executável usado. O caminho mostrado deve terminar em .venv/Scripts/python.exe nesta pasta.</p><p>O ambiente virtual separa as dependências Python do projeto. Não é uma máquina virtual nem um contentor completo: continua a usar o sistema operativo da tua máquina. Criá-lo não instala automaticamente NumPy ou PyTorch.</p><p>Usamos o caminho direto do executável, por isso não é necessário ativar o ambiente nem alterar a política de execução do PowerShell. Se um caminho completo tiver espaços, usa aspas e o operador de chamada &amp;: <code>&amp; "C:/pasta com espaços/.venv/Scripts/python.exe" ola.py</code>. Substitui este caminho ilustrativo pelo real.</p><p>Em macOS/Linux, o equivalente é criar com <code>python3 -m venv .venv</code> e executar com <code>.venv/bin/python</code>. O restante código da aula é igual.</p></section>
<section id="script"><h2>4. Um script que consegues explicar</h2><p>No editor, cria ola.py, guarda em UTF-8 e escreve:</p><pre><code>latencias = [100, 110, 390]
total = sum(latencias)
quantidade = len(latencias)
media = total / quantidade
print(media)</code></pre><p>A primeira linha atribui uma lista a latencias; os valores estão em milissegundos. sum soma os elementos: 600. len conta-os: 3. A divisão calcula 200.0, e print apresenta o resultado no terminal. Em Python, / produz uma divisão comum: 5/2 dá 2.5. O separador decimal no código é ponto, mesmo que escrevas vírgula nas contas em português.</p><p>Executa no PowerShell, na pasta do ficheiro:</p><pre><code>./.venv/Scripts/python.exe ola.py</code></pre><p>Deves ver 200.0. Altera 390 para 90, guarda e volta a executar: agora obténs 100.0. Se ainda vires 200.0, confirma que guardaste e que executaste o ficheiro certo. Cada execução de um script arranca um processo novo; não depende das variáveis de uma sessão interativa anterior.</p><h3>A lista vazia é um caso diferente</h3><p>Se latencias=[], a quantidade é zero e a divisão falha. Não inventes média zero: “não há medições” é diferente de “medimos zero”. Podes testar a lista antes da divisão e devolver None, o objeto Python que aqui significa ausência de resultado.</p><pre><code>def calcular_media(valores):
    if not valores:
        return None
    return sum(valores) / len(valores)

print(calcular_media([]))  # None</code></pre><p>def define a função. Os dois pontos iniciam um bloco e a indentação indica o que lhe pertence. O if executa o primeiro return quando a lista está vazia. return termina a chamada e devolve um valor. Não é igual a print: print mostra algo, mas não devolve esse resultado numérico ao chamador.</p><h3>Laboratório completo</h3><p><a href="../../../labs/ambiente.py">Abre ambiente.py</a>, guarda-o na pasta de prática e executa <code>./.venv/Scripts/python.exe ambiente.py</code>. O script mostra o executável, calcula média e mediana e imprime JSON. As verificações assert falham se uma expectativa não for satisfeita. O programa não cria nem altera ficheiros.</p><p>Para [100,110,390], o relatório deve mostrar quantidade 3, média 200.0 e mediana 110. Para a lista vazia, a média torna-se null no JSON, correspondente ao None em Python. A biblioteca json faz a conversão para um formato que já conheces de APIs.</p></section>
<section id="dependencias"><h2>5. O que instalar e o que guardar</h2><p>sys, json e statistics fazem parte da biblioteca padrão usada no laboratório: não precisas de pip para os instalar. Bibliotecas externas, como NumPy, são instaladas no ambiente do projeto. Quando chegares a P02, poderás usar <code>./.venv/Scripts/python.exe -m pip install numpy</code>. Não é necessário para concluir esta aula.</p><p>Usar o mesmo executável com -m pip liga a instalação ao intérprete pretendido. Para confirmar o pip, executa <code>./.venv/Scripts/python.exe -m pip --version</code>. O comando <code>./.venv/Scripts/python.exe -m pip freeze</code> lista dependências externas instaladas em formato utilizável para reprodução. Um ambiente sem pacotes externos pode produzir uma lista vazia; isso não significa que a biblioteca padrão esteja ausente.</p><p>Guarda no Git o código, instruções e requisitos do projeto. Exclui .venv/, que pode ser recriada e contém caminhos dependentes da máquina. Não confundas .venv com .env: este último nome é frequentemente usado para configurações e segredos, e não cria um ambiente Python. Consulta complementar: <a href="https://docs.python.org/3/tutorial/venv.html">ambientes e pacotes na documentação Python</a>.</p></section>
<section id="erros"><h2>6. Ler um erro como uma pista</h2><p>Começa pela última linha da mensagem para identificar o tipo de erro; depois encontra o teu ficheiro e a linha indicados no traceback, a sequência de chamadas apresentada. Um erro numa linha pode ter origem na linha anterior, por exemplo um parêntese por fechar.</p><ul><li><strong>Ficheiro não encontrado:</strong> verifica pasta atual, nome e extensão. ola.py.txt não é ola.py.</li><li><strong>SyntaxError:</strong> procura aspas, parênteses e dois pontos em falta; não copies comandos PowerShell para o código.</li><li><strong>IndentationError:</strong> confirma os blocos e usa espaços de forma consistente.</li><li><strong>NameError:</strong> o nome não foi definido nessa execução, ou há diferença de escrita. total e Total são nomes diferentes.</li><li><strong>ModuleNotFoundError:</strong> verifica o executável e o nome do módulo antes de instalar. Não chames ao teu script json.py, pois pode esconder o módulo padrão.</li><li><strong>ZeroDivisionError:</strong> verifica o denominador e o caso vazio; reinstalar Python não corrige a lógica.</li></ul><p>Treino de diagnóstico: troca intencionalmente quantidade por Quantidade numa cópia de ola.py, executa e lê o NameError. Corrige o nome e executa novamente. O objetivo é ligar a mensagem à causa, não decorar o texto do erro.</p></section>`;
b5.questions=[
choice('Muito fácil · Onde executar o comando py ola.py?',['No terminal PowerShell','Dentro do ficheiro ola.py','Na barra de endereço do navegador'],0,'O comando pede a outro programa para executar o ficheiro.','É um comando de terminal. Dentro de ola.py escreves instruções Python, como print(2+3).'),
n('Muito fácil · Qual é a saída de len([100,110,390])?',3,'len conta elementos, não soma valores.','A lista tem três elementos, por isso len devolve 3.'),
n('Fácil · Qual é a saída de sum([100,110,390]) / 3?',200,'Soma antes de dividir.','100+110+390=600; 600/3=200. Em Python será mostrado 200.0.'),
choice('Médio · O script dá ModuleNotFoundError após instalar uma biblioteca. Qual é a primeira investigação adequada?',['Reinstalar todo o Windows','Comparar o Python da execução com o Python usado por pip','Apagar o código'],1,'Duas instalações Python podem ter pacotes diferentes.','Confirma sys.executable e usa esse executável com -m pip. Verifica também o nome do import.'),
choice('Médio · Para uma lista vazia, qual é o resultado adequado da função calcular_media desta aula?',['0, porque não há números','None, para representar ausência de média','Um número aleatório'],1,'Sem observações não foi medida uma média zero.','O ramo if not valores devolve None antes de dividir. Isso evita divisão por zero sem inventar uma medição.'),
choice('Difícil · Que conjunto permite partilhar este exercício de forma reproduzível?',['Apenas a pasta .venv','Código, comandos, versão Python e requisitos externos quando existirem','Apenas uma captura do terminal'],1,'Outra pessoa precisa de recriar o ambiente e executar.','Código e instruções são a base. Regista versões e requisitos quando usados; .venv não é portável nem deve ir para o Git.'),
choice('Desafiante · O laboratório mostra média 200.0, mas após alterar o ficheiro continuas a ver o valor antigo. O que verificas primeiro?',['Se guardaste o ficheiro e estás a executar o caminho correto','Se precisas de GPU','Se o tamanho da lista é sempre zero'],0,'O resultado pode vir de uma cópia antiga.','Guarda, confirma a pasta e o nome, e executa de novo. Só investiga a fórmula depois de confirmar que o código atualizado está realmente a correr.')
];
b5.task='Executa ambiente.py num ambiente virtual e regista sys.executable e a versão Python. Altera a lista do relatório para [10,20,30,40] e prevê média e mediana antes de executar: ambas devem ser 25. Testa também a lista vazia. Explica por que None/null não é o mesmo que zero e quais os ficheiros que guardarias no Git.';
