import {lessons,n,choice} from './lessons.mjs';
import {courses} from './courses.mjs';
const b5=lessons.find(l=>l.id==='B05');
b5.complete=true;
b5.duration='2 sessões de 60 minutos';
b5.extra=String.raw`
<nav class="note" aria-label="Roteiro da aula"><h2>O resultado que queremos obter</h2><p>No fim, vais executar um script de análise de latências, identificar o Python que o executou e compreender a saída. Primeira sessão: ambiente e ficheiros. Segunda: código, diagnóstico de erros e repetição. Usa o PowerShell no Windows; não precisas de GPU, conta de cloud ou bibliotecas de IA.</p><ol><li><a href="#ferramentas">Distinguir as ferramentas</a></li><li><a href="#instalacao">Confirmar a instalação</a></li><li><a href="#ambiente">Criar o ambiente virtual</a></li><li><a href="#script">Ler e executar o primeiro script</a></li><li><a href="#dependencias">Dependências e Git</a></li><li><a href="#erros">Investigar erros</a></li></ol></nav>
<section id="ferramentas"><h2>1. Editor, terminal e intérprete têm papéis diferentes</h2><p>O editor guarda texto num ficheiro, como ola.py. O terminal recebe comandos para executar programas. O intérprete Python lê as instruções do ficheiro e executa-as. Abrir o ficheiro no editor não o executa, tal como abrir um ficheiro JavaScript não inicia automaticamente um processo Node.</p><p>Se escreveres apenas py no terminal, podes entrar no modo interativo de Python: aparece o prompt &gt;&gt;&gt;. Aí escreves instruções Python, como print(2 + 3). Para voltar ao PowerShell, escreve exit(). Não copies os símbolos &gt;&gt;&gt; para o teu ficheiro. Comandos como py ola.py pertencem ao terminal, não ao código Python.</p><p>O navegador executa o JavaScript deste site; não executa estes ficheiros Python. GitHub Pages disponibiliza o material, mas os laboratórios correm na tua máquina. Mais tarde, uma aplicação web poderá pedir previsões a um serviço Python por HTTP.</p></section>
<section id="instalacao"><h2>2. Confirmar antes de instalar</h2><p>Abre o PowerShell e executa:</p><pre><code>py --version
python --version</code></pre><p>Basta um comando funcional que identifique Python 3 para prosseguires. Se ambos funcionarem, podem apontar para instalações diferentes: não assumas que são equivalentes. Nesta aula usamos py para criar o ambiente e, depois, o caminho explícito do Python desse ambiente.</p><p>Se nenhum funcionar, consulta a <a href="https://docs.python.org/3/using/windows.html">instalação oficial em Windows</a> e obtém Python a partir de <a href="https://www.python.org/downloads/">python.org</a>. Reabre o terminal após a instalação e volta a verificar. A documentação atual descreve o Python Install Manager; uma instalação existente funcional não precisa de ser substituída para esta aula.</p><p>Se abrir a Microsoft Store em vez de mostrar uma versão, pode existir apenas um alias sem um intérprete disponível. Confirma a instalação segundo a documentação e verifica de novo. Não alteres variáveis do sistema ao acaso. Para este laboratório sem dependências externas, não precisas de escolher a versão mais recente só por ser mais recente.</p></section>
<section id="ambiente"><h2>3. Uma pasta e um ambiente por projeto</h2><p>No teu editor, cria uma pasta nova chamada pratica-ia e abre um terminal nessa pasta. Se a pasta já contiver trabalho, reutiliza-a sem apagar nada. Get-Location mostra a pasta atual; Get-ChildItem lista os ficheiros. Estes são comandos PowerShell, não Python.</p><pre><code>Get-Location
Get-ChildItem
py -m venv .venv
./.venv/Scripts/python.exe --version
./.venv/Scripts/python.exe -c "import sys; print(sys.executable)"</code></pre><p>O argumento -m pede ao Python que execute um módulo; venv cria o ambiente e .venv é a pasta de destino. O último comando executa uma pequena instrução passada como texto com -c. sys é um módulo da biblioteca padrão e sys.executable identifica o executável usado. O caminho mostrado deve terminar em .venv/Scripts/python.exe nesta pasta.</p><p>O ambiente virtual separa as dependências Python do projeto. Não é uma máquina virtual nem um contentor completo: continua a usar o sistema operativo da tua máquina. Criá-lo não instala automaticamente NumPy ou PyTorch.</p><p>Usamos o caminho direto do executável, por isso não é necessário ativar o ambiente nem alterar a política de execução do PowerShell. Se um caminho completo tiver espaços, usa aspas e o operador de chamada &amp;: <code>&amp; "C:/pasta com espaços/.venv/Scripts/python.exe" ola.py</code>. Substitui este caminho ilustrativo pelo real.</p><p>Em macOS/Linux, o equivalente é criar com <code>python3 -m venv .venv</code> e executar com <code>.venv/bin/python</code>. O restante código da aula é igual.</p></section>
<section id="script"><h2>4. Um script que consegues explicar</h2><p>No editor, cria ola.py, guarda em UTF-8 e escreve:</p><pre><code>latencias = [100, 110, 390]
total = sum(latencias)
quantidade = len(latencias)
media = total / quantidade
print(media)</code></pre><p>A primeira linha atribui uma lista a latencias; os valores estão em milissegundos. sum soma os elementos: 600. len conta-os: 3. A divisão calcula 200.0, e print apresenta o resultado no terminal. Em Python, / produz uma divisão comum: 5/2 dá 2.5. O separador decimal no código é ponto, mesmo que escrevas vírgula nas contas em português.</p><p>Executa no PowerShell, na pasta do ficheiro:</p><pre><code>./.venv/Scripts/python.exe ola.py</code></pre><p>Deves ver 200.0. Altera 390 para 90, guarda e volta a executar: agora obténs 100.0. Se ainda vires 200.0, confirma que guardaste e que executaste o ficheiro certo. Cada execução de um script arranca um processo novo; não depende das variáveis de uma sessão interativa anterior.</p><h3>A lista vazia é um caso diferente</h3><p>Se latencias=[], a quantidade é zero e a divisão falha. Não inventes média zero: “não há medições” é diferente de “medimos zero”. Podes testar a lista antes da divisão e devolver None, o objeto Python que aqui significa ausência de resultado.</p><pre><code>def calcular_media(valores):
    if not valores:
        return None
    return sum(valores) / len(valores)

print(calcular_media([]))  # None</code></pre><p>def define a função. Os dois pontos iniciam um bloco e a indentação indica o que lhe pertence. O if executa o primeiro return quando a lista está vazia. return termina a chamada e devolve um valor. Não é igual a print: print mostra algo, mas não devolve esse resultado numérico ao chamador.</p><h3>Laboratório completo</h3><p><a href="../../../labs/ambiente.py">Abre ambiente.py</a>, guarda-o na pasta de prática e executa <code>./.venv/Scripts/python.exe ambiente.py</code>. O script mostra o executável, calcula média e mediana e imprime JSON. As verificações assert falham se uma expectativa não for satisfeita. O programa não cria nem altera ficheiros.</p><p>Para [100,110,390], o relatório deve mostrar quantidade 3, média 200.0 e mediana 110. Para a lista vazia, a média torna-se null no JSON, correspondente ao None em Python. A biblioteca json faz a conversão para um formato que já conheces de APIs.</p></section>
<section id="dependencias"><h2>5. O que instalar e o que guardar</h2><p>sys, json e statistics fazem parte da biblioteca padrão usada no laboratório: não precisas de pip para os instalar. Bibliotecas externas, como NumPy, são instaladas no ambiente do projeto. Quando chegares a P02, poderás usar <code>./.venv/Scripts/python.exe -m pip install numpy</code>. Não é necessário para concluir esta aula.</p><p>Usar o mesmo executável com -m pip liga a instalação ao intérprete pretendido. Para confirmar o pip, executa <code>./.venv/Scripts/python.exe -m pip --version</code>. O comando <code>./.venv/Scripts/python.exe -m pip freeze</code> lista dependências externas instaladas em formato utilizável para reprodução. Um ambiente sem pacotes externos pode produzir uma lista vazia; isso não significa que a biblioteca padrão esteja ausente.</p><p>Guarda no Git o código, instruções e requisitos do projeto. Exclui .venv/, que pode ser recriada e contém caminhos dependentes da máquina. Não confundas .venv com .env: este último nome é frequentemente usado para configurações e segredos, e não cria um ambiente Python. Consulta complementar: <a href="https://docs.python.org/3/tutorial/venv.html">ambientes e pacotes na documentação Python</a>.</p></section>
<section id="erros"><h2>6. Ler um erro como uma pista</h2><p>Começa pela última linha da mensagem para identificar o tipo de erro; depois encontra o teu ficheiro e a linha indicados no traceback, a sequência de chamadas apresentada. Um erro numa linha pode ter origem na linha anterior, por exemplo um parêntese por fechar.</p><ul><li><strong>Ficheiro não encontrado:</strong> verifica pasta atual, nome e extensão. ola.py.txt não é ola.py.</li><li><strong>SyntaxError:</strong> procura aspas, parênteses e dois pontos em falta; não copies comandos PowerShell para o código.</li><li><strong>IndentationError:</strong> confirma os blocos e usa espaços de forma consistente.</li><li><strong>NameError:</strong> o nome não foi definido nessa execução, ou há diferença de escrita. total e Total são nomes diferentes.</li><li><strong>ModuleNotFoundError:</strong> verifica o executável e o nome do módulo antes de instalar. Não chames ao teu script json.py, pois pode esconder o módulo padrão.</li><li><strong>ZeroDivisionError:</strong> verifica o denominador e o caso vazio; reinstalar Python não corrige a lógica.</li></ul><p>Treino de diagnóstico: troca intencionalmente quantidade por Quantidade numa cópia de ola.py, executa e lê o NameError. Corrige o nome e executa novamente. O objetivo é ligar a mensagem à causa, não decorar o texto do erro.</p></section>`;
b5.questions=[
choice('Muito fácil · Onde executar o comando py ola.py?',['No terminal PowerShell','Dentro do ficheiro ola.py','Na barra de endereço do navegador'],0,'O comando pede a outro programa para executar o ficheiro.','É um comando de terminal. Dentro de ola.py escreves instruções Python, como print(2+3).'),
n('Muito fácil · Qual é a saída de len([100,110,390])?',3,'len conta elementos, não soma valores.','A lista tem três elementos, por isso len devolve 3.'),
n('Fácil · Qual é a saída de sum([100,110,390]) / 3?',200,'Soma antes de dividir.','100+110+390=600; 600/3=200. Em Python será mostrado 200.0.'),
choice('Médio · O script dá ModuleNotFoundError após instalar uma biblioteca. Qual é a primeira investigação adequada?',['Reinstalar todo o Windows','Comparar o Python da execução com o Python usado por pip','Apagar o código'],1,'Duas instalações Python podem ter pacotes diferentes.','Confirma sys.executable e usa esse executável com -m pip. Verifica também o nome do import.'),
choice('Médio · Para uma lista vazia, qual é o resultado adequado da função calcular_media desta aula?',['0, porque não há números','None, para representar ausência de média','Um número aleatório'],1,'Sem observações não foi medida uma média zero.','O ramo if not valores devolve None antes de dividir. Isso evita divisão por zero sem inventar uma medição.'),
choice('Difícil · Que conjunto permite partilhar este exercício de forma reproduzível?',['Apenas a pasta .venv','Código, comandos, versão Python e requisitos externos quando existirem','Apenas uma captura do terminal'],1,'Outra pessoa precisa de recriar o ambiente e executar.','Código e instruções são a base. Regista versões e requisitos quando usados; .venv não é portável nem deve ir para o Git.'),
choice('Desafiante · O laboratório mostra média 200.0, mas após alterar o ficheiro continuas a ver o valor antigo. O que verificas primeiro?',['Se guardaste o ficheiro e estás a executar o caminho correto','Se precisas de GPU','Se o tamanho da lista é sempre zero'],0,'O resultado pode vir de uma cópia antiga.','Guarda, confirma a pasta e o nome, e executa de novo. Só investiga a fórmula depois de confirmar que o código atualizado está realmente a correr.')
];
b5.task='Executa ambiente.py num ambiente virtual e regista sys.executable e a versão Python. Altera a lista do relatório para [10,20,30,40] e prevê média e mediana antes de executar: ambas devem ser 25. Testa também a lista vazia. Explica por que None/null não é o mesmo que zero e quais os ficheiros que guardarias no Git.';

const b6=lessons.find(l=>l.id==='B06');
b6.complete=true;
b6.duration='4 horas: diagnóstico, correção e revisão diferida';
b6.goal='Identificar lacunas concretas nas bases e decidir a próxima sessão de estudo.';
b6.prereq='B01, B02, B03, B04 e B05: estudar e tentar os exercícios; ter executado ambiente.py.';
b6.paragraphs=[
'Este diagnóstico não mede inteligência nem garante resultados académicos. Serve para observar o que consegues fazer sem apoio neste momento. A informação útil é a combinação de resposta, raciocínio e ajuda necessária.',
'Se já estudaste B01–B05, começa pelos sete exercícios sem ler os exemplos desta página. Usa papel, não consultes resoluções e regista se precisaste de pistas. Depois lê o método de correção e os exemplos. A validação indica se o valor coincide; não avalia a qualidade do raciocínio escrito.',
'Não precisas de compensar uma dificuldade estudando mais horas do que tens disponíveis. Reserva quatro horas para este ciclo e usa os erros para substituir conteúdo novo por revisão. Uma lacuna localizada é uma indicação de trabalho, não uma razão para recomeçar o curso inteiro.'
];
b6.formula='tentar sem ajuda → explicar o erro → rever a base → resolver uma variante → decidir o próximo passo';
b6.extra=`
<section class="note"><h2>Primeiro, recolhe uma tentativa honesta</h2><p>Reserva 45 minutos. <a href="#exercicios">Vai diretamente ao diagnóstico</a>. Escreve as contas antes de carregar em Verificar; uma tentativa com pista é útil para aprender, mas não conta como independente. Não marques a aula como estudada apenas porque abriste todas as soluções.</p></section>
<section><h2>1. O que registar no papel</h2><p>Cria quatro colunas: número da pergunta, passos que fizeste, resultado e apoio usado. No apoio, escreve “nenhum”, “pista” ou “resolução”. Acrescenta uma frase sobre o erro depois de corrigir. Não precisas de guardar dados pessoais nem instalar outra ferramenta.</p><p>Conta como resposta independente apenas a que conseguiste justificar antes de consultar ajuda. Se escolheste uma opção ao acaso, volta a explicar a decisão antes de a contar. Para respostas numéricas, escreve a unidade quando existe; um número correto com uma interpretação errada ainda pede revisão.</p><p>Usa primeiro o papel para frações e álgebra. Na questão de variância, podes usar uma calculadora nas operações, mas escreve a média, os desvios e o divisor escolhido. Na questão do ambiente, identifica o papel de cada executável em vez de decorar uma letra.</p></section>
<section><h2>2. Mapear cada pergunta para uma base</h2><table><caption>Roteiro de recuperação após a tentativa</caption><thead><tr><th scope="col">Questão</th><th scope="col">Competência</th><th scope="col">Revisão</th></tr></thead><tbody><tr><td>1</td><td>Somar frações equivalentes</td><td><a href="../modulo-1/b01.html#operacoes">B01 · operações</a></td></tr><tr><td>2</td><td>Parte, total e percentagem</td><td><a href="../modulo-1/b01.html#percentagens">B01 · percentagens</a></td></tr><tr><td>3</td><td>Equação com coeficiente negativo</td><td><a href="../modulo-1/b02.html#equacoes">B02 · igualdade</a></td></tr><tr><td>4</td><td>Substituir numa função</td><td><a href="../modulo-2/b03.html#funcao">B03 · função</a></td></tr><tr><td>5</td><td>Mediana em quantidade par</td><td><a href="../modulo-2/b04.html#centro">B04 · centro</a></td></tr><tr><td>6</td><td>Variância e divisor</td><td><a href="../modulo-2/b04.html#dispersao">B04 · dispersão</a></td></tr><tr><td>7</td><td>Relacionar execução e instalação</td><td><a href="b05.html#ambiente">B05 · ambiente</a></td></tr></tbody></table><p>O mapa cobre os pontos de entrada mais importantes, não cada detalhe das cinco aulas. Mesmo com sete acertos, revê uma explicação sobre domínio de funções, uma taxa de variação e a diferença entre amostra e população antes de declarar a ponte consolidada.</p></section>
<section><h2>3. Distinguir três tipos de erro</h2><p><strong>Conceptual:</strong> escolheste a operação errada, por exemplo somaste denominadores de frações ou fizeste a média sem considerar tamanhos dos grupos. Relê a intuição e reconstrói um exemplo pequeno. Repetir muitas contas com a regra errada não resolve o problema.</p><p><strong>Aritmético:</strong> escolheste o método certo, mas perdeste um sinal ou erraste uma multiplicação. Escreve uma operação por linha e verifica substituindo ou usando a operação inversa. Não é necessário reler uma cadeira inteira por uma soma isolada.</p><p><strong>Operacional:</strong> sabes a intenção, mas o código corre noutro ficheiro ou intérprete. Regista a pasta e o comando, confirma o executável e repete. Uma mensagem de erro do terminal não significa que a matemática esteja errada.</p><p>Uma pergunta pode envolver mais de um tipo. Anota a primeira decisão errada, não apenas a última resposta. “Preciso de melhorar em matemática” é demasiado amplo; “inverti a fração errada ao dividir” permite escolher a revisão.</p></section>
<section><h2>4. Usar as quatro horas sem sobrecarregar a semana</h2><ol><li><strong>45 minutos:</strong> tentativa independente dos sete exercícios e registo dos passos.</li><li><strong>45 minutos:</strong> correção, classificação dos erros e escolha de uma ou duas bases prioritárias.</li><li><strong>90 minutos:</strong> revisão dirigida, com um exemplo reconstruído e uma tarefa prática no laboratório. Divide em duas sessões curtas se ajudar.</li><li><strong>60 minutos, após pelo menos 48 horas:</strong> resolver as variantes e explicar as ideias sem consultar as notas.</li></ol><p>Total: 45+45+90+60=240 minutos, ou quatro horas. O intervalo de 48 horas é uma regra prática deste percurso para separar a leitura da recordação; não é uma garantia de retenção. Não concentres as quatro etapas na mesma noite.</p><p>Se surgirem muitas lacunas, escolhe primeiro B01 e B02, porque suportam funções e estatística. Usa outra semana de quatro horas se for necessário e desloca as aulas seguintes. O plano não te pede para eliminar sono ou descanso para cumprir uma data arbitrária.</p></section>
<section><h2>5. Decidir se avanças</h2><p><strong>Seis ou sete acertos independentes, com explicação:</strong> podes avançar, depois de rever o erro restante e executar o laboratório. <strong>Quatro ou cinco:</strong> dedica a próxima sessão às competências em falta e repete com variantes. <strong>Zero a três:</strong> regressa às bases indicadas, uma de cada vez, e reserva outro ciclo.</p><p>Estes intervalos são critérios pedagógicos propostos, não notas oficiais. Um erro de divisão por zero ou uma incapacidade de executar o script exige resolução mesmo que o total de acertos seja alto. A marca de progresso no site é manual e não verifica estes requisitos automaticamente.</p><p>Antes de abrir a primeira cadeira, deves conseguir calcular uma proporção, resolver uma equação simples, ler uma função, distinguir média de mediana e executar um script no ambiente correto. Não precisas de saber redes neuronais nesta fase.</p></section>`;
b6.exampleA=['Corrigir um erro conceptual','Numa revisão, escreveste 1/2 + 1/4 = 2/6. Em vez de decorar a resposta, representa metade como dois quartos: 2/4 + 1/4 = 3/4. O denominador conserva o tamanho das partes; o numerador conta quantas tens. Fecha a resolução e experimenta uma soma com outros denominadores.'];
b6.exampleB=['Corrigir um erro operacional','Instalaste uma biblioteca com o Python do sistema, mas executaste o script com o Python de .venv. Primeiro imprime sys.executable nessa execução. Depois usa esse executável com -m pip para verificar a instalação. Não alteres a fórmula do script para resolver uma dependência ausente.'];
b6.error='Não contes como domínio uma resposta que apenas reconheceste depois de abrir a solução. Guarda essa tentativa como aprendizagem e verifica outra vez com valores diferentes.';
b6.code='// Registo de exemplo, sem avaliação automática de domínio.\nconst tentativa = { questao: 1, semAjuda: false, tipoErro: "conceptual", rever: "B01" };\nconsole.log(tentativa.rever); // B01';
b6.questions=[
n('1 · Calcula 1/3 + 1/6. Responde em decimal.',0.5,'Usa sextos para as duas parcelas.','1/3=2/6. Soma:2/6+1/6=3/6=1/2=0,5. Se somaste denominadores, revê B01.'),
n('2 · Houve 12 sucessos em 80 tentativas. Qual é a percentagem de sucesso?',15,'O denominador é o total de tentativas.','12/80=0,15; multiplicar por 100 dá 15%. Se usaste 80/12, revê parte e total em B01.'),
n('3 · Resolve −3x + 4 = 19.',-5,'Subtrai 4 aos dois membros e divide pelo coeficiente com o sinal.','−3x=15; x=15/(−3)=−5. Verificação:−3×(−5)+4=19. Revê B02 se o sinal não ficou claro.'),
n('4 · Se f(x)=4x−2, quanto vale f(3)?',10,'Troca x por 3 antes de calcular.','4×3−2=12−2=10. f(3) é a saída, não uma equação para descobrir x. Revê B03.'),
n('5 · Qual é a mediana de 8, 2, 10 e 4?',6,'Ordena e encontra as duas posições centrais.','Ordem:2,4,8,10. Mediana=(4+8)/2=6. Revê B04 se escolheste um extremo ou não ordenaste.'),
n('6 · Qual é a variância populacional de [0,2,4,6], usando divisor n?',5,'Média 3. Faz a média dos quadrados dos desvios.','Desvios:−3,−1,1,3. Quadrados:9,1,1,9. Soma20; divide por n=4: variância5. Não é o desvio padrão nem a variância amostral.'),
choice('7 · Um pacote foi instalado com o intérprete A. O script corre com B e não encontra o pacote. Qual é o procedimento adequado?',['Usar A de novo sem verificar nada','Confirmar o caminho de B e usar esse executável com -m pip para verificar/instalar a dependência','Mudar a média dos dados'],1,'Instalação e execução precisam de referir o ambiente pretendido.','Confirma sys.executable na execução B e usa esse caminho com -m pip. Se B for o ambiente correto do projeto, verifica o pacote aí. Revê B05.')
];
b6.afterExercises=`<section><h2>Segunda tentativa: valores novos, as mesmas ideias</h2><p>Faz esta variante após 48 horas, sem consultar as resoluções. Regista respostas no papel; esta secção usa autocorreção, sem validador automático.</p><ol><li>Calcula 1/4 + 1/8 em decimal.</li><li>9 sucessos em 60 tentativas: qual é a percentagem?</li><li>Resolve −2x + 3 = 15.</li><li>Para f(x)=3x−1, calcula f(4).</li><li>Encontra a mediana de 9,1,7,3.</li><li>Calcula a variância populacional de [1,3,5], arredondada a duas casas.</li><li>Explica por que None para a média de uma lista vazia não é equivalente a zero.</li></ol><details><summary>Abrir correção apenas depois da tentativa</summary><ol><li>1/4=2/8; 2/8+1/8=3/8=0,375.</li><li>9/60=0,15; percentagem15%.</li><li>−2x=12; x=−6; verificação:12+3=15.</li><li>3×4−1=11.</li><li>Ordem1,3,7,9; mediana=(3+7)/2=5.</li><li>Média3; quadrados dos desvios4,0,4; variância8/3≈2,67.</li><li>None assinala ausência de média. Zero afirmaria uma média numérica que não foi calculada a partir de observações.</li></ol></details></section>`;
b6.task='Executa labs/ambiente.py e explica três campos do relatório sem ler o código. Escreve as duas maiores dificuldades da tentativa, os links das secções a rever e a data da variante. Acrescenta uma frase sobre domínio de funções, outra sobre taxa de variação e outra sobre representatividade. Avança só quando também conseguires justificar essas frases.';
courses.find(c=>c.id==='bases').rubric='No diagnóstico B06: pelo menos 6/7 sem pistas, raciocínio escrito, revisão dos erros e execução do laboratório. Repetir com variantes após 48 horas.';
