export const sources = {
  isla: ['ISLA Gaia — plano publicado', 'https://www.islagaia.pt/pt/pos-graduacoes/inteligencia-artificial-pt'],
  python: ['Python — tutorial oficial', 'https://docs.python.org/3/tutorial/'],
  numpy: ['NumPy — guia inicial', 'https://numpy.org/doc/stable/user/absolute_beginners.html'],
  sklearn: ['scikit-learn — primeiros passos', 'https://scikit-learn.org/stable/getting_started.html'],
  torch: ['PyTorch — Learn the Basics', 'https://docs.pytorch.org/tutorials/beginner/basics/intro.html'],
  nlp: ['Hugging Face — curso de modelos de linguagem', 'https://huggingface.co/learn/llm-course/chapter1/1'],
  google: ['Google — Machine Learning Crash Course', 'https://developers.google.com/machine-learning/crash-course']
};
export const courses = [
 {id:'bases',code:'00',title:'Ponte de bases',ects:null,color:'lime',goal:'Recuperar as ferramentas do secundário que vais usar em IA, sem repetir todo o programa.',prereq:'Operações aritméticas e leitura de JavaScript.',modules:['Números e álgebra','Funções e dados','Preparação do ambiente'],outcome:'Resolver o diagnóstico e explicar uma função, uma percentagem e uma média sem copiar uma solução.',project:'Criar uma folha de raciocínio com taxas de conversão, função de custo e resumo de latências.',rubric:'Resolver pelo menos 5 das 6 questões de diagnóstico; rever os erros 48 horas depois.',later:['Potências e logaritmos com mais exercícios','Sistemas de equações e geometria de vetores','Leitura de somatórios e notação científica'],refs:['google','python']},
 {id:'matematica',code:'01',title:'Fundamentos Matemáticos para IA',ects:4,color:'blue',goal:'Ler vetores, matrizes, probabilidades e gradientes com significado, antes de usar bibliotecas.',prereq:'Ponte de bases: frações, equações, funções e médias.',modules:['Álgebra linear aplicada','Probabilidade e otimização'],outcome:'Calcular uma previsão linear, uma probabilidade condicionada e um passo de descida do gradiente.',project:'Implementar uma previsão de latência com produto escalar e reduzir o erro de um parâmetro à mão.',rubric:'Dimensões corretas, contas justificadas e interpretação das unidades; pelo menos 2/3 exercícios por aula sem pistas.',later:['Sistemas lineares, independência e projeções','Autovalores, autovetores e intuição de PCA','Distribuições, variância amostral e inferência','Derivadas parciais, regra da cadeia e otimização multivariável'],refs:['numpy','google']},
 {id:'programacao',code:'02',title:'Programação para IA',ects:4,color:'blue',goal:'Transferir a experiência de front-end para scripts de dados e experiências reproduzíveis em Python.',prereq:'Ambiente instalado e noção de listas, funções e objetos em JavaScript.',modules:['Python para quem já programa','Dados e experiências'],outcome:'Ler dados, validar o esquema, calcular estatísticas e reproduzir a execução num ambiente isolado.',project:'Construir um script que analisa latências e exporta um relatório JSON para uma interface.',rubric:'Executa de raiz, trata dados inválidos, não mistura treino com teste e documenta comandos e dependências.',later:['pandas: seleção, groupby, junções e dados ausentes','Matplotlib e exploração visual','Testes, módulos, tipagem e tratamento de erros','Notebooks, Git, ambientes e serialização segura'],refs:['python','numpy','sklearn']},
 {id:'introducao',code:'03',title:'Introdução à Inteligência Artificial',ects:3,color:'violet',goal:'Distinguir os tipos de IA e formular problemas que podem ser avaliados com dados.',prereq:'Funções e percentagens; não exige cálculo universitário.',modules:['Problemas e paradigmas','Procura e responsabilidade'],outcome:'Escolher entre regras, aprendizagem supervisionada e não supervisionada e definir uma avaliação útil.',project:'Escrever uma proposta para classificar pedidos de suporte, incluindo alternativa sem IA e riscos.',rubric:'Problema delimitado, entradas disponíveis no momento de uso, métrica e análise de falhas concretas.',later:['História da IA, representação de conhecimento e lógica','Procura informada e heurísticas','Aprendizagem por reforço: estados, ações e recompensas','Ética, explicabilidade e documentação de dados'],refs:['google']},
 {id:'machine-learning',code:'04',title:'Machine Learning',ects:5,color:'blue',goal:'Construir e avaliar modelos simples, protegendo a experiência contra fuga de informação.',prereq:'Python, matrizes, médias e divisão entre treino e teste.',modules:['Prever e medir','Generalizar e descobrir'],outcome:'Comparar regressão e classificação com uma referência simples e justificar a divisão dos dados.',project:'Executar o laboratório de classificação de pedidos de suporte e escrever uma análise de erros.',rubric:'Referência explícita, teste separado, métrica adequada e limitações; pontuação alta por si só não basta.',later:['Regressão logística, árvores, ensembles e regularização','Validação cruzada, pipelines e procura de hiperparâmetros','Desequilíbrio, calibração e escolha de limiares','PCA, clustering e avaliação sem rótulos'],refs:['sklearn','google']},
 {id:'deep-learning',code:'05',title:'Redes Neuronais e Deep Learning',ects:5,color:'violet',goal:'Perceber o que uma rede calcula e como aprende, sem começar por arquiteturas gigantes.',prereq:'Produto escalar, derivada, Python e avaliação de Machine Learning.',modules:['Do neurónio à aprendizagem','Treino e arquiteturas'],outcome:'Calcular um neurónio, interpretar um gradiente e reconhecer sobreajustamento num treino.',project:'Executar uma pequena rede em CPU e comparar com o modelo linear do mesmo problema.',rubric:'Shapes explicadas, gradientes limpos, treino e avaliação separados, comparação honesta e reproduzível.',later:['Backpropagation por várias camadas e regra da cadeia','CNN, convolução, pooling e visão computacional','RNN, atenção e transformers','Transfer learning, regularização e comparação TensorFlow/PyTorch'],refs:['torch']},
 {id:'nlp',code:'06',title:'Processamento de Linguagem Natural',ects:3,color:'violet',goal:'Passar de texto a representações numéricas e avaliar sistemas de linguagem com espírito crítico.',prereq:'Python, classificação, produto escalar e noção de rede neuronal.',modules:['Representar texto','Modelos de linguagem e pesquisa'],outcome:'Explicar tokenização, construir uma referência de classificação e desenhar um fluxo RAG verificável.',project:'Classificar mensagens de suporte e desenhar pesquisa de documentação com indicação da fonte.',rubric:'Divisão por origem dos textos, vocabulário aprendido no treino e teste com negações e casos ambíguos.',later:['TF-IDF e classificação com pipelines','Embeddings, similaridade e pesquisa semântica','Atenção, transformers e adaptação de modelos','Avaliação de geração, recuperação e segurança de aplicações'],refs:['nlp','sklearn']},
 {id:'aplicacoes',code:'07',title:'Inteligência Artificial em Aplicações Práticas',ects:3,color:'lime',goal:'Integrar previsões numa aplicação web com contratos claros, revisão humana e avaliação de utilidade.',prereq:'HTTP/JSON e fundamentos de avaliação de modelos.',modules:['Produto e integração','Operação e impacto'],outcome:'Definir uma API de previsão, uma interface de incerteza e um plano de monitorização.',project:'Prototipar a interface do assistente de suporte e ligar ao contrato de uma API simulada.',rubric:'Estados de erro, acessibilidade, alternativa manual, minimização de dados e critérios de operação.',later:['Casos em indústria, saúde, finanças e transportes','Cloud: CPU/GPU, custos, deployment e escalabilidade','Monitorização de drift, qualidade e incidentes','Privacidade, segurança e avaliação do impacto'],refs:['google','sklearn']},
 {id:'projeto',code:'08',title:'Projeto Final',ects:3,color:'lime',goal:'Transformar os conhecimentos num pequeno projeto defensável e reproduzível.',prereq:'Programação e Machine Learning; NLP se escolheres o projeto de suporte.',modules:['Desenhar uma experiência','Entregar e defender'],outcome:'Apresentar problema, dados, referência, modelo, avaliação, interface e limitações num repositório.',project:'Assistente de triagem de suporte: sugerir categoria, permitir correção e medir falhas por categoria.',rubric:'Problema 15%, dados 20%, avaliação 25%, implementação 20%, comunicação e reflexão 20%. Grelha proposta, não oficial.',later:['Recolha e anotação de dados com critérios consistentes','Experiências comparativas e ablações','Relatório técnico e demonstração','Defesa oral e plano de evolução'],refs:['sklearn','google']}
];
