import {lessons,n,choice} from './lessons.mjs';

const m3=lessons.find(l=>l.id==='M03');
m3.complete=true;
m3.duration='2 sessões de 60 minutos';
m3.goal='Calcular probabilidades condicionadas e atualizar uma crença sem trocar o grupo de referência.';
m3.prereq='B01: frações e percentagens; B04: frequências, população e amostra.';
m3.extra=`
<nav class="note" aria-label="Roteiro da aula"><h2>Como estudar esta aula</h2><p>Primeira sessão: acontecimentos e regras. Segunda: condicionamento, independência e Bayes. Em cada pergunta escreve primeiro “entre que casos?”; esse grupo será o denominador.</p><ol><li><a href="#incerteza">Resultados e acontecimentos</a></li><li><a href="#regras-probabilidade">Complemento, união e interseção</a></li><li><a href="#condicional">Probabilidade condicionada</a></li><li><a href="#tabela-alertas">Tabela de alertas</a></li><li><a href="#independencia">Independência</a></li><li><a href="#total-bayes">Probabilidade total e Bayes</a></li><li><a href="#modelos-probabilidade">Probabilidades de um modelo</a></li></ol></nav>
<section id="incerteza"><h2>1. Descrever uma experiência incerta</h2><p>Uma experiência aleatória tem resultados cujo valor concreto ainda não conhecemos. Lançar uma moeda, observar se um pedido é urgente ou medir se um utilizador converte são exemplos. “Aleatória” descreve a incerteza do modelo; não afirma que o processo não tenha causas.</p><p>O <strong>espaço amostral</strong> Ω reúne os resultados possíveis. Para um pedido classificado apenas como urgente ou normal, Ω={urgente,normal}. Um <strong>acontecimento</strong> é um conjunto de resultados. Em dois lançamentos de moeda, Ω={CC,CK,KC,KK}, onde C é cara e K é coroa. O acontecimento A “pelo menos uma cara” é {CC,CK,KC}.</p><p>A probabilidade P(A) é um número entre 0 e 1. Zero representa impossibilidade dentro do modelo; um representa certeza dentro do modelo. Em percentagem, o intervalo é de 0% a 100%. Para espaços finitos com resultados igualmente prováveis, P(A)=casos favoráveis/casos possíveis. A igualdade de probabilidades é uma hipótese, não uma consequência de contar resultados.</p><p>Nos dois lançamentos de uma moeda equilibrada e independentes, cada sequência tem probabilidade 1/4. Logo P(pelo menos uma cara)=3/4. Para dados observados, 30 urgentes em 100 pedidos dão frequência relativa 0,30; usamos essa frequência para descrever a amostra e, com cuidado, estimar uma probabilidade futura.</p></section>
<section id="regras-probabilidade"><h2>2. Combinar acontecimentos sem contar duas vezes</h2><p>O complemento Aᶜ contém os resultados em que A não acontece. Como A e o seu complemento cobrem todo o espaço sem sobreposição, P(Aᶜ)=1−P(A). Se P(erro)=0,08, então P(sem erro)=0,92.</p><p>A interseção A∩B significa que A <strong>e</strong> B acontecem. A união A∪B significa que acontece A <strong>ou</strong> B, incluindo ambos. Em linguagem matemática, “ou” é normalmente inclusivo.</p><figure><svg viewBox="0 0 500 220" role="img" aria-label="Dois círculos sobrepostos A e B; a zona central representa A e B"><rect x="25" y="20" width="450" height="175" rx="8" fill="#f8faf9" stroke="#172323"/><circle cx="210" cy="105" r="72" fill="#7ca1e0" fill-opacity=".45" stroke="#4265d6"/><circle cx="290" cy="105" r="72" fill="#b0d56e" fill-opacity=".45" stroke="#648671"/><path d="M250 45C278 58 290 80 290 105C290 131 278 153 250 166C222 153 210 131 210 105C210 80 222 58 250 45Z" fill="#678b9a" fill-opacity=".55"/><g font-size="17" fill="#172323"><text x="165" y="110">A</text><text x="327" y="110">B</text><text x="222" y="108">A ∩ B</text><text x="35" y="215">Ω: todos os resultados</text></g></svg><figcaption>A interseção está nos dois acontecimentos. Na união, conta-se toda a área de A e B uma única vez.</figcaption></figure><p>A regra da união é P(A∪B)=P(A)+P(B)−P(A∩B). Subtraímos a interseção porque foi contada uma vez em P(A) e outra em P(B). Se 40% usam móvel, 30% usam modo escuro e 15% fazem ambos, a probabilidade de usar pelo menos um é 0,40+0,30−0,15=0,55.</p><p>Dois acontecimentos são mutuamente exclusivos quando não podem ocorrer juntos: A∩B é vazio e a sua probabilidade é zero. Nesse caso, a união é a soma. “Urgente” e “normal” podem ser exclusivos numa classificação binária; “móvel” e “modo escuro” não são.</p></section>
<section id="condicional"><h2>3. Condicionar muda o universo da pergunta</h2><p>P(A|B) lê-se “probabilidade de A sabendo B”. A barra vertical significa “dado que”. Restringimos a atenção aos casos em B e perguntamos que fração também pertence a A.</p><div class="formula">P(A|B) = P(A ∩ B) / P(B), desde que P(B) &gt; 0</div><p>Em contagens, a mesma ideia é número de casos com A e B dividido pelo número de casos com B. Escreve o denominador em palavras. Para P(urgente|alerta), o denominador são todos os alertas. Para P(alerta|urgente), são todos os urgentes. As expressões normalmente diferem.</p><p>Se B tem probabilidade zero, esta fórmula elementar não define P(A|B): estaríamos a dividir por zero. Em teoria avançada existem formas de condicionamento para variáveis contínuas, mas não precisas delas aqui.</p><p>Condicionar não significa que B causou A. P(conversão|móvel) compara conversões dentro de visitas móveis; não prova que o dispositivo causou a diferença. Outros fatores podem variar entre os grupos.</p></section>
<section id="tabela-alertas"><h2>4. Uma tabela 2×2 mantém os denominadores visíveis</h2><p>Há 100 pedidos: 10 urgentes e 90 normais. Um sistema emite alerta em 8 urgentes e 18 normais.</p><table><caption>Alertas e urgência real</caption><thead><tr><th scope="col">Resultado do sistema</th><th scope="col">Urgente</th><th scope="col">Normal</th><th scope="col">Total</th></tr></thead><tbody><tr><th scope="row">Alerta</th><td>8</td><td>18</td><td>26</td></tr><tr><th scope="row">Sem alerta</th><td>2</td><td>72</td><td>74</td></tr><tr><th scope="row">Total</th><td>10</td><td>90</td><td>100</td></tr></tbody></table><p>P(alerta|urgente)=8/10=0,80: entre os urgentes, detetou 80%. P(urgente|alerta)=8/26≈0,3077: entre os alertas, cerca de 30,77% eram urgentes. A primeira será chamada sensibilidade ou recall em Machine Learning; a segunda, precisão dos alertas.</p><p>Os 18 alertas em pedidos normais são falsos positivos. Os 2 urgentes sem alerta são falsos negativos. Qual erro é mais grave depende da aplicação; a matemática não escolhe a consequência aceitável.</p><p>A taxa de falsos positivos entre normais é P(alerta|normal)=18/90=0,20. Não uses 18/100: isso é a proporção de toda a amostra que é simultaneamente alerta e normal, P(alerta∩normal)=0,18.</p></section>
<section id="independencia"><h2>5. Independência significa “saber B não muda A”</h2><p>A e B são independentes quando P(A|B)=P(A), desde que P(B)&gt;0. Uma forma equivalente é P(A∩B)=P(A)P(B). Se a probabilidade de A é 0,4 e a de B é 0,5 e são independentes, a interseção tem probabilidade 0,2.</p><p>Exemplo com moeda equilibrada: A é “primeiro lançamento dá cara” e B é “segundo lançamento dá cara”. P(A)=1/2 e P(A|B)=1/2. Saber o segundo resultado não altera o primeiro neste modelo.</p><p>Independência não é o mesmo que acontecimentos mutuamente exclusivos. Se A e B forem exclusivos e ambos tiverem probabilidade positiva, observar B torna A impossível: P(A|B)=0, diferente de P(A). Portanto são dependentes.</p><p>Em dados de utilizadores, observações repetidas da mesma pessoa podem não ser independentes. Sessões partilham hábitos, dispositivo e contexto. Assumir independência apenas porque as linhas estão separadas no CSV pode produzir avaliações demasiado otimistas.</p></section>
<section id="total-bayes"><h2>6. Reunir caminhos e inverter a condição</h2><h3>Probabilidade total</h3><p>Se todo pedido é urgente U ou normal N, e os grupos são exclusivos, um alerta pode surgir por dois caminhos. P(alerta)=P(alerta|U)P(U)+P(alerta|N)P(N). No exemplo: 0,8×0,1+0,2×0,9=0,08+0,18=0,26. Isto coincide com 26 alertas em 100.</p><h3>Regra de Bayes</h3><p>Bayes inverte a condição usando a frequência de base:</p><div class="formula">P(U|alerta) = P(alerta|U) × P(U) / P(alerta)</div><p>Substitui: 0,8×0,1/0,26=0,08/0,26≈0,3077. A conta recupera os 8 urgentes entre 26 alertas. P(U)=0,1 é a probabilidade a priori, antes de observar o alerta; P(U|alerta) é a posterior, depois da evidência.</p><p>A verosimilhança P(alerta|U)=0,8 não é a posterior. O denominador P(alerta) considera todos os caminhos que produzem o alerta. A classe urgente é rara, por isso os falsos alertas dos muitos casos normais pesam bastante.</p><h3>O efeito da frequência de base</h3><p>Mantém P(alerta|U)=0,8 e P(alerta|N)=0,2, mas imagina que 50% dos pedidos são urgentes. P(alerta)=0,8×0,5+0,2×0,5=0,5. A posterior passa a 0,8×0,5/0,5=0,8. O mesmo sistema de deteção produz alertas muito mais informativos numa população com mais urgentes.</p><p>Antes de aplicar uma taxa de um estudo a outro contexto, verifica se a população e as frequências de base mudaram. Bayes não corrige dados enviesados nem garante que as taxas condicionais permaneçam estáveis.</p></section>
<section id="modelos-probabilidade"><h2>7. O número de um modelo precisa de validação</h2><p>Um classificador pode devolver um score entre 0 e 1. Isso não o torna automaticamente uma probabilidade correta. Um modelo está calibrado quando, entre casos a que atribui cerca de 0,7, aproximadamente 70% são positivos, avaliado em dados adequados. Calibração é diferente de ordenar bem os casos.</p><p>Escolher um limiar, como emitir alerta acima de 0,5, transforma score em decisão. Alterar o limiar muda falsos positivos e falsos negativos. A escolha depende das consequências e deve ser feita em validação, não ajustada repetidamente ao teste final.</p><p>Probabilidades também dependem do conjunto de acontecimentos definido. Se “urgente” estiver rotulado de forma inconsistente, P(urgente|alerta) mede essa definição instável. Especifica rótulos, população, período e método de recolha.</p><p>O código desta aula calcula a tabela com contagens. Mantém os nomes longos de propósito: tornam o denominador legível antes da divisão.</p></section>
<section class="note"><h2>Verificação conceptual</h2><p>Explica a diferença entre “entre urgentes, quantos receberam alerta?” e “entre alertas, quantos eram urgentes?”. Depois explica por que dois acontecimentos exclusivos com probabilidade positiva não são independentes.</p></section>`;
m3.questions=[
n('Muito fácil · Se P(erro)=0,08, qual é P(sem erro)? Responde em decimal.',0.92,'Usa o complemento: as duas probabilidades somam 1.','P(sem erro)=1−0,08=0,92.'),
n('Muito fácil · Em 40 visitas móveis, 10 convertem. Qual é P(conversão|móvel)?',0.25,'O denominador são as visitas móveis.','10/40=0,25, equivalente a 25%.'),
n('Fácil · P(A)=0,4, P(B)=0,3 e P(A∩B)=0,1. Quanto vale P(A∪B)?',0.6,'Soma A e B e retira a interseção contada duas vezes.','0,4+0,3−0,1=0,6.'),
n('Médio · Na tabela da aula, qual é P(alerta|normal), em percentagem?',20,'Entre os 90 normais, 18 receberam alerta.','18/90=0,20=20%. Não uses 18/100.'),
n('Médio · P(A)=0,5 e P(B)=0,4. Se A e B são independentes, quanto vale P(A∩B)?',0.2,'Para independência, multiplica as probabilidades.','P(A∩B)=0,5×0,4=0,2.'),
choice('Difícil · Dois acontecimentos mutuamente exclusivos com probabilidades positivas são independentes?',['Sim','Não'],1,'Se B acontece, pode A acontecer também?','Não. Se são exclusivos, P(A|B)=0, mas P(A)>0; observar B altera a probabilidade de A.'),
n('Desafiante · P(U)=0,05, P(alerta|U)=0,9 e P(alerta|normal)=0,1. Qual é P(U|alerta), em percentagem? Arredonda a duas casas.',32.14,'Calcula primeiro P(alerta) pelos dois caminhos.','P(alerta)=0,9×0,05+0,1×0,95=0,045+0,095=0,14. Bayes:0,045/0,14≈0,321428; em percentagem≈32,14%. A taxa de deteção de 90% não é a probabilidade posterior.')
];
m3.task='Desenha uma tabela para 200 pedidos: 20 urgentes; há alerta em 15 urgentes e 36 normais. Calcula P(alerta|urgente), P(urgente|alerta), P(alerta|normal) e P(alerta). Confere depois: 75%, aproximadamente 29,41%, 20% e 25,5%. Explica por que os primeiros dois valores diferem e identifica os dois tipos de erro.';
m3.code='urgentes = 10\nnormais = 90\nalerta_urgente = 8\nalerta_normal = 18\n\np_alerta_dado_urgente = alerta_urgente / urgentes\np_alerta_dado_normal = alerta_normal / normais\np_urgente = urgentes / (urgentes + normais)\np_normal = 1 - p_urgente\np_alerta = p_alerta_dado_urgente * p_urgente + p_alerta_dado_normal * p_normal\np_urgente_dado_alerta = p_alerta_dado_urgente * p_urgente / p_alerta\n\nassert abs(p_alerta - 0.26) < 1e-12\nassert abs(p_urgente_dado_alerta - 8 / 26) < 1e-12\nprint({"P(alerta)": p_alerta, "P(urgente|alerta)": p_urgente_dado_alerta})';
