import {lessons,n,choice} from './lessons.mjs';

const m3=lessons.find(l=>l.id==='M03');
m3.complete=true;
m3.duration='2 sessões de 60 minutos';
m3.goal='Calcular probabilidades condicionadas e atualizar uma crença sem trocar o grupo de referência.';
m3.prereq='B01: frações e percentagens; B04: frequências, população e amostra.';
m3.extra=`
<nav class="note" aria-label="Roteiro da aula"><h2>Como estudar esta aula</h2><p>Primeira sessão: acontecimentos e regras. Segunda: condicionamento, independência e Bayes. Em cada pergunta escreve primeiro “entre que casos?”; esse grupo será o denominador.</p><ol><li><a href="#incerteza">Resultados e acontecimentos</a></li><li><a href="#regras-probabilidade">Complemento, união e interseção</a></li><li><a href="#condicional">Probabilidade condicionada</a></li><li><a href="#tabela-alertas">Tabela de alertas</a></li><li><a href="#independencia">Independência</a></li><li><a href="#total-bayes">Probabilidade total e Bayes</a></li><li><a href="#modelos-probabilidade">Probabilidades de um modelo</a></li></ol></nav>
<section id="incerteza"><h2>1. Descrever uma experiência incerta</h2><p>Uma experiência aleatória tem resultados cujo valor concreto ainda não conhecemos. Lançar uma moeda, observar se um pedido é urgente ou medir se um utilizador converte são exemplos. “Aleatória” descreve a incerteza do modelo; não afirma que o processo não tenha causas.</p><p>O <strong>espaço amostral</strong> Ω reúne os resultados possíveis. Para um pedido classificado apenas como urgente ou normal, Ω={urgente,normal}. Um <strong>acontecimento</strong> é um conjunto de resultados. Em dois lançamentos de moeda, Ω={CC,CK,KC,KK}, onde C é cara e K é coroa. O acontecimento A “pelo menos uma cara” é {CC,CK,KC}.</p><p>A probabilidade P(A) é um número entre 0 e 1. Zero representa impossibilidade dentro do modelo; um representa certeza dentro do modelo. Em percentagem, o intervalo é de 0% a 100%. Para espaços finitos com resultados igualmente prováveis, P(A)=casos favoráveis/casos possíveis. A igualdade de probabilidades é uma hipótese, não uma consequência de contar resultados.</p><p>Nos dois lançamentos de uma moeda equilibrada e independentes, cada sequência tem probabilidade 1/4. Logo P(pelo menos uma cara)=3/4. Para dados observados, 30 urgentes em 100 pedidos dão frequência relativa 0,30; usamos essa frequência para descrever a amostra e, com cuidado, estimar uma probabilidade futura.</p></section>
<section id="regras-probabilidade"><h2>2. Combinar acontecimentos sem contar duas vezes</h2><p>O complemento Aᶜ contém os resultados em que A não acontece. Como A e o seu complemento cobrem todo o espaço sem sobreposição, P(Aᶜ)=1−P(A). Se P(erro)=0,08, então P(sem erro)=0,92.</p><p>A interseção A∩B significa que A <strong>e</strong> B acontecem. A união A∪B significa que acontece A <strong>ou</strong> B, incluindo ambos. Em linguagem matemática, “ou” é normalmente inclusivo.</p><figure><svg viewBox="0 0 500 220" role="img" aria-label="Dois círculos sobrepostos A e B; a zona central representa A e B"><rect x="25" y="20" width="450" height="175" rx="8" fill="#f8faf9" stroke="#172323"/><circle cx="210" cy="105" r="72" fill="#7ca1e0" fill-opacity=".45" stroke="#4265d6"/><circle cx="290" cy="105" r="72" fill="#b0d56e" fill-opacity=".45" stroke="#648671"/><path d="M250 45C278 58 290 80 290 105C290 131 278 153 250 166C222 153 210 131 210 105C210 80 222 58 250 45Z" fill="#678b9a" fill-opacity=".55"/><g font-size="17" fill="#172323"><text x="165" y="110">A</text><text x="327" y="110">B</text><text x="222" y="108">A ∩ B</text><text x="35" y="215">Ω: todos os resultados</text></g></svg><figcaption>A interseção está nos dois acontecimentos. Na união, conta-se toda a área de A e B uma única vez.</figcaption></figure><p>A regra da união é P(A∪B)=P(A)+P(B)−P(A∩B). Subtraímos a interseção porque foi contada uma vez em P(A) e outra em P(B). Se 40% usam móvel, 30% usam modo escuro e 15% fazem ambos, a probabilidade de usar pelo menos um é 0,40+0,30−0,15=0,55.</p><p>Dois acontecimentos são mutuamente exclusivos quando não podem ocorrer juntos: A∩B é vazio e a sua probabilidade é zero. Nesse caso, a união é a soma. “Urgente” e “normal” podem ser exclusivos numa classificação binária; “móvel” e “modo escuro” não são.</p></section>
<section id="condicional"><h2>3. Condicionar muda o universo da pergunta</h2><p>P(A|B) lê-se “probabilidade de A sabendo B”. A barra vertical significa “dado que”. Restringimos a atenção aos casos em B e perguntamos que fração também pertence a A.</p><div class="formula">P(A|B) = P(A ∩ B) / P(B), desde que P(B) &gt; 0</div><p>Em contagens, a mesma ideia é número de casos com A e B dividido pelo número de casos com B. Escreve o denominador em palavras. Para P(urgente|alerta), o denominador são todos os alertas. Para P(alerta|urgente), são todos os urgentes. As expressões normalmente diferem.</p><p>Se B tem probabilidade zero, esta fórmula elementar não define P(A|B): estaríamos a dividir por zero. Em teoria avançada existem formas de condicionamento para variáveis contínuas, mas não precisas delas aqui.</p><p>Condicionar não significa que B causou A. P(conversão|móvel) compara conversões dentro de visitas móveis; não prova que o dispositivo causou a diferença. Outros fatores podem variar entre os grupos.</p></section>
<section id="tabela-alertas"><h2>4. Uma tabela 2×2 mantém os denominadores visíveis</h2><p>Há 100 pedidos: 10 urgentes e 90 normais. Um sistema emite alerta em 8 urgentes e 18 normais.</p><table><caption>Alertas e urgência real</caption><thead><tr><th scope="col">Resultado do sistema</th><th scope="col">Urgente</th><th scope="col">Normal</th><th scope="col">Total</th></tr></thead><tbody><tr><th scope="row">Alerta</th><td>8</td><td>18</td><td>26</td></tr><tr><th scope="row">Sem alerta</th><td>2</td><td>72</td><td>74</td></tr><tr><th scope="row">Total</th><td>10</td><td>90</td><td>100</td></tr></tbody></table><p>P(alerta|urgente)=8/10=0,80: entre os urgentes, detetou 80%. P(urgente|alerta)=8/26≈0,3077: entre os alertas, cerca de 30,77% eram urgentes. A primeira será chamada sensibilidade ou recall em Machine Learning; a segunda, precisão dos alertas.</p><p>Os 18 alertas em pedidos normais são falsos positivos. Os 2 urgentes sem alerta são falsos negativos. Qual erro é mais grave depende da aplicação; a matemática não escolhe a consequência aceitável.</p><p>A taxa de falsos positivos entre normais é P(alerta|normal)=18/90=0,20. Não uses 18/100: isso é a proporção de toda a amostra que é simultaneamente alerta e normal, P(alerta∩normal)=0,18.</p></section>
<section id="independencia"><h2>5. Independência significa “saber B não muda A”</h2><p>A e B são independentes quando P(A|B)=P(A), desde que P(B)&gt;0. Uma forma equivalente é P(A∩B)=P(A)P(B). Se a probabilidade de A é 0,4 e a de B é 0,5 e são independentes, a interseção tem probabilidade 0,2.</p><p>Exemplo com moeda equilibrada: A é “primeiro lançamento dá cara” e B é “segundo lançamento dá cara”. P(A)=1/2 e P(A|B)=1/2. Saber o segundo resultado não altera o primeiro neste modelo.</p><p>Independência não é o mesmo que acontecimentos mutuamente exclusivos. Se A e B forem exclusivos e ambos tiverem probabilidade positiva, observar B torna A impossível: P(A|B)=0, diferente de P(A). Portanto são dependentes.</p><p>Em dados de utilizadores, observações repetidas da mesma pessoa podem não ser independentes. Sessões partilham hábitos, dispositivo e contexto. Assumir independência apenas porque as linhas estão separadas no CSV pode produzir avaliações demasiado otimistas.</p></section>
<section id="total-bayes"><h2>6. Reunir caminhos e inverter a condição</h2><h3>Probabilidade total</h3><p>Se todo pedido é urgente U ou normal N, e os grupos são exclusivos, um alerta pode surgir por dois caminhos. P(alerta)=P(alerta|U)P(U)+P(alerta|N)P(N). No exemplo: 0,8×0,1+0,2×0,9=0,08+0,18=0,26. Isto coincide com 26 alertas em 100.</p><h3>Regra de Bayes</h3><p>Bayes inverte a condição usando a frequência de base:</p><div class="formula">P(U|alerta) = P(alerta|U) × P(U) / P(alerta)</div><p>Substitui: 0,8×0,1/0,26=0,08/0,26≈0,3077. A conta recupera os 8 urgentes entre 26 alertas. P(U)=0,1 é a probabilidade a priori, antes de observar o alerta; P(U|alerta) é a posterior, depois da evidência.</p><p>A verosimilhança P(alerta|U)=0,8 não é a posterior. O denominador P(alerta) considera todos os caminhos que produzem o alerta. A classe urgente é rara, por isso os falsos alertas dos muitos casos normais pesam bastante.</p><h3>O efeito da frequência de base</h3><p>Mantém P(alerta|U)=0,8 e P(alerta|N)=0,2, mas imagina que 50% dos pedidos são urgentes. P(alerta)=0,8×0,5+0,2×0,5=0,5. A posterior passa a 0,8×0,5/0,5=0,8. O mesmo sistema de deteção produz alertas muito mais informativos numa população com mais urgentes.</p><p>Antes de aplicar uma taxa de um estudo a outro contexto, verifica se a população e as frequências de base mudaram. Bayes não corrige dados enviesados nem garante que as taxas condicionais permaneçam estáveis.</p></section>
<section id="modelos-probabilidade"><h2>7. O número de um modelo precisa de validação</h2><p>Um classificador pode devolver um score entre 0 e 1. Isso não o torna automaticamente uma probabilidade correta. Um modelo está calibrado quando, entre casos a que atribui cerca de 0,7, aproximadamente 70% são positivos, avaliado em dados adequados. Calibração é diferente de ordenar bem os casos.</p><p>Escolher um limiar, como emitir alerta acima de 0,5, transforma score em decisão. Alterar o limiar muda falsos positivos e falsos negativos. A escolha depende das consequências e deve ser feita em validação, não ajustada repetidamente ao teste final.</p><p>Probabilidades também dependem do conjunto de acontecimentos definido. Se “urgente” estiver rotulado de forma inconsistente, P(urgente|alerta) mede essa definição instável. Especifica rótulos, população, período e método de recolha.</p><p>O código desta aula calcula a tabela com contagens. Mantém os nomes longos de propósito: tornam o denominador legível antes da divisão.</p></section>
<section class="note"><h2>Verificação conceptual</h2><p>Explica a diferença entre “entre urgentes, quantos receberam alerta?” e “entre alertas, quantos eram urgentes?”. Depois explica por que dois acontecimentos exclusivos com probabilidade positiva não são independentes.</p></section>`;
m3.questions=[
n('Muito fácil · Se P(erro)=0,08, qual é P(sem erro)? Responde em decimal.',0.92,'Usa o complemento: as duas probabilidades somam 1.','P(sem erro)=1−0,08=0,92.'),
n('Muito fácil · Em 40 visitas móveis, 10 convertem. Qual é P(conversão|móvel)?',0.25,'O denominador são as visitas móveis.','10/40=0,25, equivalente a 25%.'),
n('Fácil · P(A)=0,4, P(B)=0,3 e P(A∩B)=0,1. Quanto vale P(A∪B)?',0.6,'Soma A e B e retira a interseção contada duas vezes.','0,4+0,3−0,1=0,6.'),
n('Médio · Na tabela da aula, qual é P(alerta|normal), em percentagem?',20,'Entre os 90 normais, 18 receberam alerta.','18/90=0,20=20%. Não uses 18/100.'),
n('Médio · P(A)=0,5 e P(B)=0,4. Se A e B são independentes, quanto vale P(A∩B)?',0.2,'Para independência, multiplica as probabilidades.','P(A∩B)=0,5×0,4=0,2.'),
choice('Difícil · Dois acontecimentos mutuamente exclusivos com probabilidades positivas são independentes?',['Sim','Não'],1,'Se B acontece, pode A acontecer também?','Não. Se são exclusivos, P(A|B)=0, mas P(A)>0; observar B altera a probabilidade de A.'),
n('Desafiante · P(U)=0,05, P(alerta|U)=0,9 e P(alerta|normal)=0,1. Qual é P(U|alerta), em percentagem? Arredonda a duas casas.',32.14,'Calcula primeiro P(alerta) pelos dois caminhos.','P(alerta)=0,9×0,05+0,1×0,95=0,045+0,095=0,14. Bayes:0,045/0,14≈0,321428; em percentagem≈32,14%. A taxa de deteção de 90% não é a probabilidade posterior.')
];
m3.task='Desenha uma tabela para 200 pedidos: 20 urgentes; há alerta em 15 urgentes e 36 normais. Calcula P(alerta|urgente), P(urgente|alerta), P(alerta|normal) e P(alerta). Confere depois: 75%, aproximadamente 29,41%, 20% e 25,5%. Explica por que os primeiros dois valores diferem e identifica os dois tipos de erro.';
m3.code='urgentes = 10\nnormais = 90\nalerta_urgente = 8\nalerta_normal = 18\n\np_alerta_dado_urgente = alerta_urgente / urgentes\np_alerta_dado_normal = alerta_normal / normais\np_urgente = urgentes / (urgentes + normais)\np_normal = 1 - p_urgente\np_alerta = p_alerta_dado_urgente * p_urgente + p_alerta_dado_normal * p_normal\np_urgente_dado_alerta = p_alerta_dado_urgente * p_urgente / p_alerta\n\nassert abs(p_alerta - 0.26) < 1e-12\nassert abs(p_urgente_dado_alerta - 8 / 26) < 1e-12\nprint({"P(alerta)": p_alerta, "P(urgente|alerta)": p_urgente_dado_alerta})';

const m4=lessons.find(l=>l.id==='M04');
m4.complete=true;
m4.duration='2 sessões de 60 minutos';
m4.goal='Calcular derivadas e usar o gradiente para reduzir uma função de perda passo a passo.';
m4.prereq='B02: álgebra; B03: funções, declive e potências; M01: vetores.';
m4.extra=`
<nav class="note" aria-label="Roteiro da aula"><h2>Como estudar esta aula</h2><p>Primeira sessão: da taxa média à derivada e respetivas regras. Segunda: gradientes, perda e atualizações. Faz as primeiras duas iterações no papel antes de mover os controlos da visualização.</p><ol><li><a href="#taxa-media">Taxa média</a></li><li><a href="#derivada">Taxa instantânea e derivada</a></li><li><a href="#regras-derivacao">Regras básicas</a></li><li><a href="#cadeia">Regra da cadeia</a></li><li><a href="#parciais">Derivadas parciais e gradiente</a></li><li><a href="#perda">Função de perda</a></li><li><a href="#descida">Descida do gradiente</a></li><li><a href="#verificar-gradiente">Verificação numérica</a></li></ol></nav>
<section id="taxa-media"><h2>1. Começar pelo declive que já conheces</h2><p>A taxa média de variação de f entre x e x+h é [f(x+h)−f(x)]/h, com h≠0. h representa a alteração da entrada. É o declive da reta secante que passa por dois pontos do gráfico.</p><p>Para f(x)=x², começa em x=2 e usa h=1. f(2)=4 e f(3)=9. A taxa média é (9−4)/1=5. Se usares h=0,5, comparas 2 com 2,5: (6,25−4)/0,5=2,25/0,5=4,5. Com h=0,1: (4,41−4)/0,1=4,1.</p><p>À medida que h se aproxima de zero, a taxa aproxima-se de 4. Não colocamos h=0 na fração, porque dividir por zero não está definido. Observamos o valor para o qual as taxas tendem.</p><figure><svg viewBox="0 0 500 280" role="img" aria-label="Parábola y igual a x ao quadrado com uma reta secante entre os pontos x igual a 2 e x igual a 3 e uma tangente em x igual a 2"><path d="M45 235H465 M75 255V25" stroke="#172323" fill="none"/><path d="M75 235 Q235 235 435 35" stroke="#4265d6" stroke-width="3" fill="none"/><path d="M230 190L410 55" stroke="#9b6924" stroke-width="3"/><path d="M185 226L350 116" stroke="#277249" stroke-width="3"/><g fill="#172323" font-size="14"><text x="300" y="30">f(x)=x²</text><text x="345" y="72">secante</text><text x="205" y="205">tangente em x=2</text></g><g fill="#4265d6"><circle cx="235" cy="195" r="6"/><circle cx="315" cy="145" r="6"/></g></svg><figcaption>A secante usa dois pontos. A tangente representa a taxa instantânea no limite em que o segundo ponto se aproxima.</figcaption></figure><p>As coordenadas do desenho são ilustrativas; as contas dão os valores exatos. Uma taxa tem unidades “saída por entrada”. Se f mede erro em ms² e x é um peso em ms/imagem, a unidade da derivada combina essas unidades. Não interpretes um gradiente sem saber o que cada variável representa.</p></section>
<section id="derivada"><h2>2. A derivada mede a sensibilidade local</h2><p>A derivada de f no ponto x é o limite das taxas médias quando h tende para zero:</p><div class="formula">f′(x) = limite quando h→0 de [f(x+h)−f(x)] / h</div><p>f′ lê-se “f linha”. O símbolo → significa “tende para”. A derivada pode ser vista como declive da tangente ao gráfico ou sensibilidade da saída a uma pequena alteração da entrada.</p><p>Para f(x)=x², desenvolve a diferença: [(x+h)²−x²]/h. Como (x+h)²=x²+2xh+h², o numerador fica 2xh+h². Para h≠0, divide por h e obtém 2x+h. Quando h tende para zero, o resultado tende para 2x. Portanto f′(x)=2x.</p><p>Em x=2, f′(2)=4. Isto não diz que f(2)=4 por coincidência; são perguntas distintas que aqui dão o mesmo número. Em x=3, f(3)=9 e f′(3)=6.</p><p>Se f′(x)&gt;0, a função cresce localmente; se f′(x)&lt;0, decresce localmente. Se f′(x)=0, a tangente é horizontal, mas o ponto pode ser mínimo, máximo ou nenhum deles. Em f(x)=x³, f′(0)=0 e a função continua a crescer através de zero.</p><p>Nem toda a função é derivável em todos os pontos. |x| tem um canto em zero: o declive pela esquerda é −1 e pela direita é 1. Como não coincidem, a derivada em zero não existe.</p></section>
<section id="regras-derivacao"><h2>3. Regras básicas, sempre com significado</h2><table><caption>Derivadas usadas neste percurso</caption><thead><tr><th scope="col">Função</th><th scope="col">Derivada</th><th scope="col">Leitura</th></tr></thead><tbody><tr><td>c, constante</td><td>0</td><td>Não varia com x</td></tr><tr><td>x</td><td>1</td><td>A saída muda como a entrada</td></tr><tr><td>xⁿ</td><td>n xⁿ⁻¹</td><td>Regra da potência, para os casos estudados</td></tr><tr><td>a f(x)</td><td>a f′(x)</td><td>O escalar multiplica a sensibilidade</td></tr><tr><td>f(x)+g(x)</td><td>f′(x)+g′(x)</td><td>Somam-se as sensibilidades</td></tr></tbody></table><p>Exemplo: f(x)=3x²−4x+7. Deriva termo a termo: a derivada de 3x² é 3×2x=6x; a de −4x é −4; a da constante 7 é 0. Logo f′(x)=6x−4. Em x=2, f′(2)=12−4=8.</p><p>A regra da potência reduz o expoente por uma unidade depois de o usar como multiplicador. Para x³, a derivada é 3x². Não é x² e não é 3x³. Para x⁰=1, a regra dá 0×x⁻¹=0 onde a expressão é considerada; a derivada da constante é zero.</p><p>Uma derivada é uma nova função. f′(x)=6x−4 permite calcular o declive em qualquer x do domínio. f′(2)=8 é um único valor. Não confundas a fórmula com a sua avaliação.</p></section>
<section id="cadeia"><h2>4. Quando uma função está dentro de outra</h2><p>A regra da cadeia aparece quando compões funções. Se y=g(u) e u=f(x), uma alteração em x muda u, que muda y. A sensibilidade total multiplica as duas sensibilidades:</p><div class="formula">dy/dx = (dy/du) × (du/dx)</div><p>Considera L(w)=(2w+1)². A função interior é u=2w+1; a exterior é L=u². A derivada da exterior em relação a u é 2u. A derivada da interior em relação a w é 2. Multiplica: dL/dw=2(2w+1)×2=4(2w+1).</p><p>Em w=1, u=3 e dL/dw=12. Se esquecesses a derivada da função interior, obterias 6. Substituir primeiro e derivar depois seria inválido: L(1)=9 é uma constante e perderias a informação sobre como L varia perto de 1.</p><p>Na notação dL/dw, o numerador identifica a saída cuja mudança observamos e o denominador o parâmetro alterado. Esta notação ajuda a acompanhar a regra da cadeia em redes neuronais.</p></section>
<section id="parciais"><h2>5. Vários parâmetros produzem um gradiente</h2><p>Se uma função depende de w e b, podemos variar um enquanto mantemos o outro temporariamente fixo. A derivada parcial em relação a w escreve-se ∂L/∂w; o símbolo ∂ assinala uma derivada parcial.</p><p>Para L(w,b)=(w−2)²+(b+1)², temos ∂L/∂w=2(w−2) e ∂L/∂b=2(b+1). O gradiente reúne essas derivadas na mesma ordem dos parâmetros:</p><div class="formula">∇L(w,b) = [∂L/∂w, ∂L/∂b]</div><p>No ponto (w,b)=(0,0), o gradiente é [−4,2]. A primeira componente diz que aumentar w tende a reduzir L localmente, porque o declive atual em w é negativo. A segunda diz que aumentar b tende a aumentar L, por isso a direção de descida deverá diminuir b.</p><p>O gradiente aponta na direção de maior crescimento local segundo a geometria euclidiana dos parâmetros. O seu oposto aponta para a maior descida local. Multiplicar por uma taxa controla o tamanho do passo.</p><p>Tal como num vetor de dados, a ordem importa: [∂L/∂w,∂L/∂b] tem de ser aplicada a [w,b]. Escalas muito diferentes entre parâmetros podem tornar o percurso difícil; otimizadores e normalização ajudam, mas não substituem a verificação da função de perda.</p></section>
<section id="perda"><h2>6. Uma função de perda transforma erro em objetivo</h2><p>Uma perda atribui um número ao desvio entre previsão e alvo. Para uma observação, a perda quadrática é L=(ŷ−y)². ŷ é a previsão e y o valor observado. O quadrado torna positivos os erros em ambas as direções e penaliza mais os erros grandes.</p><p>Num modelo ŷ=wx com x=2 e alvo y=6, L(w)=(2w−6)². Pela regra da cadeia: dL/dw=2(2w−6)×2=4(2w−6). Em w=1, a previsão é 2, o erro é −4, a perda é 16 e o gradiente é 4×(−4)=−16.</p><p>Para várias observações, o erro quadrático médio é MSE=(1/n)Σ(ŷᵢ−yᵢ)². A média torna a escala menos dependente do número de exemplos. A derivada da média é a média das derivadas, quando as operações são válidas.</p><p>A perda é uma escolha de modelação. MSE está em unidades do alvo ao quadrado e dá muito peso a valores extremos. Minimizar MSE não garante que a métrica de produto, a equidade ou a utilidade melhorem.</p></section>
<section id="descida"><h2>7. Descer na direção oposta ao gradiente</h2><p>A atualização de descida do gradiente é parâmetro novo = parâmetro atual − α×gradiente. A letra grega α, alfa, é a taxa de aprendizagem. Subtraímos porque o gradiente aponta para crescimento.</p><p>Usa L(w)=(w−3)², cujo gradiente é 2(w−3). Começa em w₀=0 e α=0,1:</p><table><caption>Primeiros passos da descida</caption><thead><tr><th scope="col">Passo</th><th scope="col">w</th><th scope="col">L(w)</th><th scope="col">Gradiente</th><th scope="col">Novo w</th></tr></thead><tbody><tr><td>0</td><td>0</td><td>9</td><td>−6</td><td>0−0,1×(−6)=0,6</td></tr><tr><td>1</td><td>0,6</td><td>5,76</td><td>−4,8</td><td>0,6−0,1×(−4,8)=1,08</td></tr><tr><td>2</td><td>1,08</td><td>3,6864</td><td>−3,84</td><td>1,464</td></tr></tbody></table><p>O parâmetro aproxima-se de 3 e a perda diminui. O gradiente também perde magnitude. Nesta parábola, o mínimo global é w=3 e L=0.</p><p>Se α=2 no primeiro passo, w passa de 0 para 12 e a perda sobe de 9 para 81. A direção inicial estava certa, mas o passo saltou demasiado longe. Uma taxa muito pequena pode avançar lentamente; uma grande pode oscilar ou divergir.</p><p>Gradiente zero não garante mínimo global. Pode ser máximo ou ponto de sela em várias dimensões. E numa função não convexa, diferentes inícios podem chegar a regiões diferentes. O exemplo quadrático é deliberadamente simples.</p><p>No treino real, podes parar após um número de épocas, quando a melhoria é pequena ou segundo desempenho de validação. Não escolhes a paragem usando repetidamente o teste final. Também não assumes que perda de treino menor significa melhor generalização.</p></section>
<section id="verificar-gradiente"><h2>8. Verificar uma derivada numericamente</h2><p>Uma diferença central aproxima a derivada usando valores dos dois lados:</p><div class="formula">f′(x) ≈ [f(x+ε)−f(x−ε)] / (2ε)</div><p>ε, epsilon, é um número pequeno e positivo. Para f(w)=(w−3)² em w=1 e ε=0,001, a aproximação fica muito perto de −4, o gradiente analítico 2(1−3).</p><p>Se ε for grande, a secante não representa bem a vizinhança. Se for extremamente pequeno no computador, erros de arredondamento podem dominar. Esta verificação encontra muitos erros de sinais e regra da cadeia, mas uma correspondência num ponto não prova toda a implementação.</p><p><a href="../../../labs/gradiente.py">Executa gradiente.py</a>. O laboratório compara gradiente analítico e numérico, imprime os passos da tabela e demonstra que α=2 aumenta a perda no primeiro passo.</p></section>
<section class="note"><h2>Verificação conceptual</h2><p>Explica por que não substituímos h=0 na razão, por que a direção de descida é o oposto do gradiente e por que uma taxa de aprendizagem faz parte da atualização. Depois distingue perda, gradiente e parâmetro.</p></section>`;
m4.questions=[
n('Muito fácil · Para f(x)=3x+2, qual é f′(x)? Responde com o seu valor constante.',3,'A derivada de 3x é 3 e a da constante é zero.','f′(x)=3+0=3. A reta tem declive constante 3.'),
n('Muito fácil · Para f(x)=x², quanto vale f′(4)?',8,'A derivada é 2x.','f′(x)=2x; f′(4)=2×4=8.'),
n('Fácil · Qual é a taxa média de f(x)=x² entre x=2 e x=3?',5,'Usa [f(3)−f(2)]/(3−2).','(9−4)/(3−2)=5/1=5. A derivada em 2 seria 4; são conceitos relacionados, mas diferentes.'),
n('Médio · Para L(w,b)=(w−2)²+(b+1)², qual é a segunda componente do gradiente em (0,0)?',2,'Deriva em relação a b e substitui b=0.','∂L/∂b=2(b+1). Em b=0, dá 2. O gradiente completo é [−4,2].'),
n('Médio · w=1, gradiente=−4 e α=0,1. Qual é o novo w?',1.4,'Subtrair um número negativo aumenta o parâmetro.','w novo=1−0,1×(−4)=1+0,4=1,4.'),
n('Difícil · Para L(w)=(2w+1)², quanto vale dL/dw em w=1?',12,'Usa a derivada da função exterior e multiplica pela derivada de 2w+1.','dL/dw=2(2w+1)×2=4(2w+1). Em w=1:4×3=12.'),
n('Desafiante · Em L(w)=(w−3)², começa w₀=0 com α=0,1. Qual é w após dois passos?',1.08,'Calcula e atualiza o gradiente depois do primeiro passo.','Passo1: gradiente−6, w₁=0,6. Passo2: gradiente=2(0,6−3)=−4,8; w₂=0,6−0,1×(−4,8)=1,08.')
];
m4.task='Calcula três passos para L(w)=(w−3)², começando em 0 com α=0,1. Confere w:0,6;1,08;1,464 e perdas:5,76;3,6864;aproximadamente2,3593. Depois repete apenas o primeiro passo com α=2 e explica por que a perda sobe para81. Usa a visualização e gradiente.py só depois das contas.';
m4.code='def perda(w):\n    return (w - 3) ** 2\n\ndef gradiente(w):\n    return 2 * (w - 3)\n\nw = 0.0\ntaxa = 0.1\nfor passo in range(3):\n    anterior = perda(w)\n    w = w - taxa * gradiente(w)\n    atual = perda(w)\n    assert atual < anterior\n    print(passo + 1, round(w, 4), round(atual, 4))';
