import {lessons,n,choice} from './lessons.mjs';

const m1=lessons.find(l=>l.id==='M01');
m1.complete=true;
m1.duration='2 sessões de 60 minutos';
m1.goal='Representar dados por vetores, calcular operações e interpretar uma previsão ponderada.';
m1.prereq='B02: expressões e equações; B03: plano cartesiano, funções e raiz quadrada.';
m1.extra=`
<nav class="note" aria-label="Roteiro da aula"><h2>Como estudar esta aula</h2><p>Na primeira sessão, trabalha componentes, operações e geometria. Na segunda, aprende norma, distância e produto escalar e aplica-os a uma previsão. Escreve os vetores completos em cada linha: a posição de cada número faz parte do significado.</p><ol><li><a href="#escalares">Escalares e vetores</a></li><li><a href="#representacoes">Geometria e dados</a></li><li><a href="#operacoes-vetores">Operações</a></li><li><a href="#norma-distancia">Norma e distância</a></li><li><a href="#produto-escalar">Produto escalar</a></li><li><a href="#previsao-linear">Previsão ponderada</a></li></ol></nav>
<section id="escalares"><h2>1. De um número para uma lista com significado</h2><p>Um <strong>escalar</strong> é um único número, como 120 ms, 3 imagens ou −2. Um <strong>vetor</strong> é uma lista ordenada de números tratada como um objeto: x=[3,2]. Neste exemplo, a primeira componente pode ser o número de imagens e a segunda o número de scripts.</p><p>Os parênteses retos indicam a lista neste curso. Também encontrarás vetores escritos como colunas. A orientação depende da convenção e da operação; não muda os valores. A dimensão de [3,2] é 2, porque tem duas componentes. Não confundas dimensão do vetor com o valor de uma componente.</p><p>A ordem é um contrato. Se definimos x=[imagens,scripts], então [3,2] descreve três imagens e dois scripts. [2,3] descreve outro caso. Antes de calcular, escreve a legenda: x₁=imagens e x₂=scripts. O índice 1 identifica a primeira componente; não é uma potência.</p><p>Uma componente pode ser zero ou negativa quando o significado o permite. Uma variação de −5 ms é possível; uma contagem de −5 imagens não é. A matemática oferece operações, mas o domínio do problema decide quais os vetores válidos.</p></section>
<section id="representacoes"><h2>2. O mesmo vetor pode ser deslocamento ou dados</h2><p>Na geometria, v=[3,2] pode significar deslocar três unidades na horizontal e duas na vertical. Se começares na origem (0,0), a ponta fica no ponto (3,2). Se começares em (1,4), a ponta fica em (4,6). O vetor representa o deslocamento; o ponto representa uma posição.</p><figure><svg viewBox="0 0 500 280" role="img" aria-label="Plano cartesiano com um vetor da origem até ao ponto três vírgula dois"><defs><marker id="seta-m1" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#4265d6"/></marker></defs><path d="M55 235H455 M75 255V25" stroke="#172323" fill="none"/><g stroke="#d9e2df"><path d="M175 25V235 M275 25V235 M375 25V235 M75 165H455 M75 95H455"/></g><path d="M75 235L375 95" stroke="#4265d6" stroke-width="4" marker-end="url(#seta-m1)"/><circle cx="375" cy="95" r="6" fill="#4265d6"/><g fill="#172323" font-size="14"><text x="62" y="253">0</text><text x="170" y="253">1</text><text x="270" y="253">2</text><text x="370" y="253">3</text><text x="52" y="170">1</text><text x="52" y="100">2</text><text x="382" y="90">(3,2)</text><text x="215" y="145">v=[3,2]</text></g></svg><figcaption>O vetor v=[3,2] tem componente horizontal 3 e vertical 2.</figcaption></figure><p>Em Machine Learning, um vetor de características representa uma observação. A geometria fornece ideias de direção e distância, mas as componentes agora podem ter significados e unidades diferentes.</p><table><caption>Contrato do vetor de uma página</caption><thead><tr><th scope="col">Posição</th><th scope="col">Característica</th><th scope="col">Unidade</th><th scope="col">Valor</th></tr></thead><tbody><tr><td>x₁</td><td>Imagens</td><td>contagem</td><td>3</td></tr><tr><td>x₂</td><td>Scripts</td><td>contagem</td><td>2</td></tr></tbody></table><p>Um vetor não se torna uma boa representação só por conter números. Se trocares a ordem no treino e na utilização, os pesos são aplicados às características erradas. Se uma coluna estiver em bytes e outra em megabytes, a escala muda apesar de descreverem o mesmo fenómeno.</p></section>
<section id="operacoes-vetores"><h2>3. Operações componente a componente</h2><h3>Adição e subtração</h3><p>Só somamos vetores da mesma dimensão, componente a componente. [1,2]+[3,−1]=[1+3,2+(−1)]=[4,1]. Geometricamente, executar um deslocamento e depois outro soma os deslocamentos. Em dados, somar observações nem sempre tem interpretação útil; confirma o contexto.</p><p>Subtrair encontra a diferença por componente: [5,3]−[2,7]=[3,−4]. Se os vetores forem pontos, esta diferença é o deslocamento do segundo para o primeiro. Repara na ordem: [2,7]−[5,3]=[−3,4], o vetor oposto.</p><h3>Multiplicação por escalar</h3><p>Multiplicar um vetor pelo escalar 2 multiplica todas as componentes: 2[3,−1]=[6,−2]. O comprimento duplica e a direção mantém-se. Multiplicar por −1 dá [−3,1]: mesmo comprimento e sentido oposto. Multiplicar por zero dá o vetor zero [0,0].</p><p>Não somes um vetor de dimensão 2 a um de dimensão 3: [1,2]+[3,4,5] não está definido nesta operação. Bibliotecas podem oferecer outras regras, como broadcasting, mas isso não altera a definição da soma vetorial.</p><h3>Propriedades que podes verificar</h3><p>A adição é comutativa: u+v=v+u. É também associativa: (u+v)+w=u+(v+w). O vetor zero não altera a soma. E a multiplicação distribui-se: a(u+v)=au+av. Verifica com u=[1,2], v=[3,4] e a=2 antes de aceitar a regra.</p></section>
<section id="norma-distancia"><h2>4. Norma: o comprimento de um vetor</h2><p>A norma euclidiana de v=[v₁,v₂] escreve-se ||v|| e calcula-se por √(v₁²+v₂²). É o teorema de Pitágoras: as componentes são os catetos e o vetor é a hipotenusa. Para [3,4], ||v||=√(9+16)=5.</p><p>A norma nunca é negativa. Vale zero apenas para o vetor zero. Multiplicar um vetor por −2 multiplica a norma por |−2|=2: o sinal muda o sentido, não cria comprimento negativo.</p><p>A distância euclidiana entre a e b é a norma da diferença: d(a,b)=||a−b||. Para a=[1,1] e b=[4,5], a diferença pode ser b−a=[3,4], e a distância é 5. Usar a−b daria [−3,−4], com a mesma norma.</p><p>Um vetor não nulo pode ser normalizado para comprimento 1: v/||v||. Para [3,4], o vetor unitário é [3/5,4/5]=[0,6;0,8]. O vetor zero não pode ser normalizado, porque exigiria dividir por zero.</p><h3>Escala e unidades</h3><p>Com x=[imagens,bytes], a diferença de um milhão de bytes pode dominar a distância face a uma imagem. Isso não prova que bytes sejam mais importantes; reflete a unidade escolhida. Converter bytes para megabytes altera os números e as distâncias. Mais tarde aprenderás a normalizar características usando estatísticas do treino.</p></section>
<section id="produto-escalar"><h2>5. Produto escalar: combinar e comparar</h2><p>O produto escalar de u e v com a mesma dimensão multiplica componentes correspondentes e soma: u·v=u₁v₁+u₂v₂+…+uₙvₙ. O resultado é um escalar. Para [1,2]·[3,4], temos 1×3+2×4=3+8=11.</p><p>Não o confundas com o produto componente a componente, que produziria [3,8]. O produto escalar é comutativo: u·v=v·u. Também distribui sobre somas: u·(v+w)=u·v+u·w. Estas propriedades explicam parte do comportamento dos modelos lineares.</p><p>Geometricamente, u·v=||u|| ||v|| cos(θ), em que θ é o ângulo entre os vetores e cos é o cosseno. Se ambos são não nulos:</p><ul><li>produto positivo: ângulo inferior a 90°, direções em parte semelhantes;</li><li>produto zero: ângulo de 90°, vetores perpendiculares;</li><li>produto negativo: ângulo superior a 90°, direções em parte opostas.</li></ul><p>Exemplo: [1,0]·[0,2]=0. São perpendiculares. Mas um produto zero também ocorre se um vetor for zero; nesse caso não existe uma direção nem um ângulo definido para ele.</p><p>O produto escalar cresce com os comprimentos. [1,0]·[10,0]=10 e [1,0]·[2,0]=2, embora as direções coincidam. A similaridade do cosseno divide pelas normas para comparar direção; só está definida para vetores não nulos e também não garante que duas observações tenham o mesmo significado.</p></section>
<section id="previsao-linear"><h2>6. Uma previsão linear é um produto escalar mais um viés</h2><p>Define x=[imagens,scripts]=[3,2]. Os pesos são w=[20,50], com 20 ms por imagem e 50 ms por script. O produto w·x é 20×3+50×2=60+100=160 ms. Se houver um custo fixo b=40 ms, a previsão é ŷ=w·x+b=200 ms.</p><p>O símbolo ŷ lê-se “y chapéu” e indica uma previsão, distinguindo-a do valor observado y. O viés b, também chamado termo independente, é a previsão quando todas as características valem zero. Não é o mesmo que enviesamento social ou estatístico; a palavra tem significados diferentes.</p><table><caption>Contribuições para a previsão</caption><thead><tr><th scope="col">Componente</th><th scope="col">Entrada</th><th scope="col">Peso</th><th scope="col">Contribuição</th></tr></thead><tbody><tr><td>Imagens</td><td>3</td><td>20 ms/imagem</td><td>60 ms</td></tr><tr><td>Scripts</td><td>2</td><td>50 ms/script</td><td>100 ms</td></tr><tr><td>Viés</td><td>—</td><td>—</td><td>40 ms</td></tr><tr><th scope="row">Total</th><td></td><td></td><td>200 ms</td></tr></tbody></table><p>As unidades confirmam a conta: imagens×ms/imagem=ms. Se uma entrada estiver em megabytes, o peso dessa posição precisa de uma unidade compatível, como ms/MB. Trocar imagens e scripts sem trocar pesos produz um número calculável e semanticamente errado.</p><p>Nesta aula os pesos foram escolhidos manualmente. Treinar um modelo linear significa estimá-los a partir de dados segundo uma função de perda. Uma contribuição grande não prova causalidade: o peso descreve o modelo e depende das características, escalas e dados usados.</p></section>
<section class="note"><h2>Verificação conceptual</h2><p>Explica, sem fórmula, a diferença entre vetor, norma e produto escalar. Depois justifica por que [3 imagens,2 scripts] não pode ser trocado por [2 imagens,3 scripts] quando os pesos mantêm a ordem original.</p></section>`;
m1.questions=[
n('Muito fácil · Quantas dimensões tem o vetor [4,−1,7]?',3,'Conta as componentes, não os valores diferentes de zero.','O vetor tem três componentes e dimensão 3.'),
n('Muito fácil · Qual é a primeira componente de [1,2]+[3,−1]?',4,'Soma as primeiras componentes.','Primeira componente:1+3=4. O vetor completo é [4,1].'),
n('Fácil · Qual é a segunda componente de −2[3,−4]?',8,'Multiplica também o sinal da segunda componente.','−2[3,−4]=[−6,8]. A segunda componente vale 8.'),
n('Médio · Qual é a norma de [6,8]?',10,'Usa Pitágoras: raiz da soma dos quadrados.','||[6,8]||=√(36+64)=√100=10.'),
n('Médio · Qual é a distância entre [1,1] e [4,5]?',5,'Calcula a diferença e depois a norma.','[4,5]−[1,1]=[3,4]; √(3²+4²)=5.'),
choice('Difícil · O que podes concluir de [2,0]·[0,−3]=0?',['São perpendiculares e ambos são não nulos','São o mesmo vetor','Têm necessariamente comprimento zero'],0,'Verifica primeiro se algum é o vetor zero.','Ambos são não nulos e o produto escalar é zero; o ângulo entre eles é 90°. Portanto são perpendiculares.'),
n('Desafiante · x=[4 imagens,3 scripts], w=[15 ms/imagem,40 ms/script] e b=30 ms. Qual é a previsão em ms?',210,'Soma as contribuições e acrescenta o custo fixo.','w·x+b=15×4+40×3+30=60+120+30=210 ms. As unidades de cada contribuição são milissegundos.')
];
m1.task='No papel, usa a=[2,−1] e b=[−3,4]. Calcula a+b, a−b, 2a, ||a|| e a·b. Confere depois: [−1,3], [5,−5], [4,−2], √5≈2,24 e −10. Explica por que a norma tem unidade da componente e o produto escalar combina unidades. Depois altera uma entrada no exemplo de latência e prevê a direção da mudança antes de calcular.';
m1.code='from math import sqrt\n\ndef dot(a, b):\n    if len(a) != len(b):\n        raise ValueError("Os vetores precisam da mesma dimensão")\n    return sum(x * y for x, y in zip(a, b))\n\ndef norma(v):\n    return sqrt(dot(v, v))\n\nx = [3, 2]\nw = [20, 50]\nb = 40\nprevisao = dot(w, x) + b\nassert previsao == 200\nassert norma([3, 4]) == 5\nprint({"previsao_ms": previsao, "norma": norma([3, 4])})';

const m2=lessons.find(l=>l.id==='M02');
m2.complete=true;
m2.duration='2 sessões de 60 minutos';
m2.goal='Organizar observações em matrizes e executar produtos com dimensões justificadas.';
m2.prereq='M01: vetores, componentes, produto escalar e previsão linear.';
m2.extra=`
<nav class="note" aria-label="Roteiro da aula"><h2>Como estudar esta aula</h2><p>Na primeira sessão, lê matrizes, shapes, índices e operações simples. Na segunda, calcula produtos matriz-vetor e matriz-matriz e executa o laboratório. Antes de cada produto, escreve as dimensões no papel.</p><ol><li><a href="#matriz">Matriz, linhas e colunas</a></li><li><a href="#operacoes-matrizes">Operações simples</a></li><li><a href="#transposta">Transposta</a></li><li><a href="#matriz-vetor">Produto matriz-vetor</a></li><li><a href="#matriz-matriz">Produto matriz-matriz</a></li><li><a href="#transformacoes">Identidade e transformações</a></li><li><a href="#numpy">NumPy, @ e broadcasting</a></li></ol></nav>
<section id="matriz"><h2>1. Uma matriz organiza números em linhas e colunas</h2><p>Uma matriz é uma tabela retangular de números. Escrevemos X com letra maiúscula e dizemos que tem dimensão, ou <em>shape</em>, número de linhas × número de colunas. A matriz abaixo tem duas linhas e três colunas, portanto shape 2×3.</p><div class="formula">X = [[1, 2, 3], [4, 5, 6]] &nbsp; → &nbsp; shape 2×3</div><p>Em dados de Machine Learning, uma convenção frequente é uma observação por linha e uma característica por coluna. O contrato tem de ser explícito; uma biblioteca não sabe que a primeira coluna representa imagens.</p><table><caption>Matriz X de duas páginas e três características</caption><thead><tr><th scope="col">Observação</th><th scope="col">Imagens</th><th scope="col">Scripts</th><th scope="col">Tamanho (MB)</th></tr></thead><tbody><tr><th scope="row">Página A</th><td>3</td><td>2</td><td>1,5</td></tr><tr><th scope="row">Página B</th><td>1</td><td>4</td><td>0,8</td></tr></tbody></table><p>A matriz numérica é [[3,2,1,5],[1,4,0,8]] quando usamos vírgula decimal na escrita portuguesa; em Python, escrevemos 1.5 e 0.8. Tem n=2 observações e d=3 características, logo shape n×d=2×3.</p><p>O elemento Xᵢⱼ está na linha i e coluna j. Os índices matemáticos desta aula começam em 1: X₂₃=0,8. Em NumPy, os índices começam em 0, por isso o mesmo elemento é X[1,2]. Distingue convenção matemática de sintaxe de código.</p><p>Uma matriz precisa de linhas do mesmo comprimento. [[1,2],[3]] não é uma matriz retangular 2×2. NumPy moderno pode rejeitar a criação como array numérico regular ou criar estruturas inadequadas se forçares um tipo de objetos; corrige os dados em vez de esconder o problema.</p></section>
<section id="operacoes-matrizes"><h2>2. Igualdade, adição e multiplicação por escalar</h2><p>Duas matrizes são iguais quando têm a mesma shape e todos os elementos correspondentes são iguais. Uma matriz 2×3 nunca é igual a uma 3×2, mesmo que tenha os mesmos seis números.</p><p>A adição exige a mesma shape e atua elemento a elemento. Se A=[[1,2],[3,4]] e B=[[5,6],[7,8]], então A+B=[[6,8],[10,12]]. Pensa em sobrepor as tabelas: cada célula encontra exatamente uma célula correspondente.</p><p>Subtração segue a mesma regra. A−B é diferente de B−A; os resultados são opostos. A matriz zero, com zeros em todas as posições, é o elemento neutro da adição.</p><p>Multiplicar por um escalar multiplica todas as células. Para 2A, obténs [[2,4],[6,8]]. Não altera a shape. Em dados, converter segundos para milissegundos pode ser multiplicar uma coluna por 1000, mas não deves multiplicar colunas com outras unidades.</p><p>A expressão A*B em NumPy multiplica elementos correspondentes, sujeita às regras de broadcasting. Não representa, em geral, o produto matricial desta aula. Por exemplo, se A e B forem 2×2, A*B produz [[5,12],[21,32]].</p></section>
<section id="transposta"><h2>3. Transpor troca linhas por colunas</h2><p>A transposta de X escreve-se Xᵀ. A primeira linha torna-se a primeira coluna, a segunda linha torna-se a segunda coluna, e assim sucessivamente.</p><div class="formula">[[1, 2, 3], [4, 5, 6]]ᵀ = [[1, 4], [2, 5], [3, 6]]</div><p>A shape passa de 2×3 para 3×2. O elemento que estava em Xᵢⱼ passa para a posição j,i. Transpor duas vezes recupera a matriz original: (Xᵀ)ᵀ=X.</p><p>Transpor não significa inverter uma matriz. Uma inversa é outra operação, só existe para certas matrizes quadradas e será estudada mais tarde. Xᵀ existe para qualquer matriz retangular.</p><p>Em dados, Xᵀ coloca características nas linhas e observações nas colunas. Isto pode ser útil numa fórmula, mas não altera o contrato conceptual: tens de saber qual orientação cada operação espera.</p></section>
<section id="matriz-vetor"><h2>4. Produto matriz-vetor: várias previsões de uma vez</h2><p>Se X tem shape n×d e w tem d componentes, Xw está definido e produz n valores. Cada linha de X faz um produto escalar com w. A dimensão interior d tem de coincidir.</p><p>Usa X=[[1,2],[3,0]] e w=[10,20]. X tem shape 2×2 e w tem dimensão 2. Para a primeira saída, faz [1,2]·[10,20]=1×10+2×20=50. Para a segunda, [3,0]·[10,20]=3×10+0×20=30. Portanto Xw=[50,30].</p><table><caption>Produto linha a linha</caption><thead><tr><th scope="col">Linha de X</th><th scope="col">Produto com w</th><th scope="col">Saída</th></tr></thead><tbody><tr><td>[1,2]</td><td>1×10+2×20</td><td>50</td></tr><tr><td>[3,0]</td><td>3×10+0×20</td><td>30</td></tr></tbody></table><p>Para uma previsão linear, adiciona o mesmo viés b a cada saída: Xw+b. Com b=5, tens [55,35]. Conceptualmente, b é um escalar aplicado às n previsões. NumPy usa broadcasting para essa adição.</p><p>Uma matriz 4×3 aceita um vetor de três pesos e devolve quatro previsões. Não aceita um vetor de quatro pesos nesta orientação: o número de pesos corresponde às colunas, não às linhas.</p><p>Se precisares de duas saídas por observação, por exemplo duas pontuações, substituis o vetor w por uma matriz de pesos W com shape d×2. Então XW terá shape n×2. Esta é a ponte para o produto matriz-matriz.</p></section>
<section id="matriz-matriz"><h2>5. Produto matricial: linha por coluna</h2><p>O produto AB está definido quando o número de colunas de A coincide com o número de linhas de B. Se A tem shape m×n e B tem shape n×p, o resultado C=AB tem shape m×p. As dimensões interiores n coincidem; as exteriores m e p formam a saída.</p><div class="formula">(m×n) @ (n×p) → (m×p)</div><p>Cada célula Cᵢⱼ é o produto escalar da linha i de A com a coluna j de B. Considera A=[[1,2],[3,4]], shape 2×2, e B=[[5,6],[7,8]], também 2×2:</p><table><caption>Cálculo de C=AB</caption><thead><tr><th scope="col">Célula</th><th scope="col">Linha por coluna</th><th scope="col">Valor</th></tr></thead><tbody><tr><td>C₁₁</td><td>[1,2]·[5,7]</td><td>1×5+2×7=19</td></tr><tr><td>C₁₂</td><td>[1,2]·[6,8]</td><td>1×6+2×8=22</td></tr><tr><td>C₂₁</td><td>[3,4]·[5,7]</td><td>3×5+4×7=43</td></tr><tr><td>C₂₂</td><td>[3,4]·[6,8]</td><td>3×6+4×8=50</td></tr></tbody></table><p>Logo AB=[[19,22],[43,50]]. O produto BA também está definido neste caso, mas dá [[23,34],[31,46]]. Em geral, AB≠BA: produto matricial não é comutativo.</p><p>Uma matriz 4×3 pode multiplicar uma 3×2, produzindo 4×2. A ordem inversa, 3×2 vezes 4×3, não está definida porque 2≠4. Não tentes resolver a incompatibilidade transpondo ao acaso: isso muda a operação e o significado.</p><p>O produto é associativo quando as dimensões permitem: (AB)C=A(BC). Também distribui sobre a adição. A ordem dos fatores continua fixa. Estas propriedades permitem organizar uma cadeia de transformações de formas computacionalmente diferentes sem alterar o resultado matemático.</p></section>
<section id="transformacoes"><h2>6. Matrizes como transformações</h2><p>Uma matriz 2×2 pode transformar um vetor do plano. A matriz identidade I=[[1,0],[0,1]] mantém qualquer vetor: Iv=v. A primeira saída copia a primeira componente e a segunda copia a segunda.</p><p>A matriz S=[[2,0],[0,3]] transforma [x,y] em [2x,3y]: estica a direção horizontal por 2 e a vertical por 3. Para v=[1,2], Sv=[2,6]. Esta interpretação liga o produto a transformações visuais que conheces de gráficos e interfaces.</p><p>A matriz R=[[0,−1],[1,0]] transforma [x,y] em [−y,x], uma rotação de 90° no sentido anti-horário. Para [2,1], Rv=[−1,2]. Podes confirmar que a norma se mantém: √5 antes e depois.</p><p>Duas transformações sucessivas correspondem a um produto matricial. Se aplicas primeiro S e depois R, obténs R(Sv)=(RS)v. A matriz mais próxima do vetor atua primeiro. Trocar RS por SR pode mudar o resultado, tal como a ordem de funções compostas em B03.</p><p>Uma matriz que envia direções diferentes para o mesmo resultado perde informação. Nem toda a transformação pode ser desfeita por uma matriz inversa. Nesta aula basta reconhecer a possibilidade; determinantes e inversas ficam para aprofundamento.</p></section>
<section id="numpy"><h2>7. Traduzir a notação para NumPy</h2><p>NumPy representa vetores e matrizes com arrays. shape informa as dimensões; dtype informa o tipo dos elementos. Confirma ambas quando os resultados surpreendem.</p><pre><code>import numpy as np

X = np.array([[1., 2.], [3., 0.]])
w = np.array([10., 20.])
print(X.shape)       # (2, 2)
print(w.shape)       # (2,)
print(X @ w)         # [50. 30.]
print(X * X)         # produto elemento a elemento
print(X.T)           # transposta</code></pre><p>Um vetor com shape (2,) não mostra orientação de linha ou coluna. Um array [[10],[20]] tem shape (2,1). Em certas operações, os resultados diferem. Para previsões e alvos, verifica shapes exatas em vez de confiar que broadcasting fará o pretendido.</p><p>Broadcasting permite operar arrays de shapes compatíveis sem copiar explicitamente valores. Somar um escalar 5 a [50,30] dá [55,35]. Somar um vetor de duas colunas a uma matriz 3×2 aplica esse vetor a cada linha. É útil, mas pode esconder erros.</p><p>Exemplo perigoso: previsões com shape (3,1) menos alvos com shape (3,) pode produzir shape (3,3), comparando cada previsão com todos os alvos. O código corre, mas calcula nove erros. Se queres três diferenças, usa shapes iguais, como (3,) e (3,), ou (3,1) e (3,1).</p><p><a href="../../../labs/algebra_linear.py">Executa o laboratório algebra_linear.py</a>. Ele verifica shapes, produto matriz-vetor, produto matriz-matriz, identidade, rotação e a diferença entre <code>*</code> e <code>@</code>.</p></section>
<section class="note"><h2>Verificação conceptual</h2><p>Antes dos exercícios, explica por que (4×3)@(3×2) produz 4×2 e por que a célula (i,j) usa a linha i do primeiro fator e a coluna j do segundo. Depois distingue transposta, produto elemento a elemento e produto matricial.</p></section>`;
m2.questions=[
n('Muito fácil · Uma matriz representa 12 páginas, uma por linha, e 3 características por página. Quantas linhas tem?',12,'Uma observação ocupa cada linha.','A shape é 12×3, por isso há 12 linhas.'),
n('Muito fácil · X tem shape 5×4. Quantas colunas tem Xᵀ?',5,'A transposta troca linhas por colunas.','Xᵀ tem shape 4×5, portanto tem 5 colunas.'),
n('Fácil · A=[[1,2],[3,4]] e B=[[5,6],[7,8]]. Qual é o elemento da primeira linha e segunda coluna de A+B?',8,'Soma as células na mesma posição.','A₁₂+B₁₂=2+6=8. A+B=[[6,8],[10,12]].'),
n('Médio · X=[[1,2],[3,0]] e w=[10,20]. Qual é a segunda saída de Xw?',30,'Faz o produto escalar da segunda linha com w.','[3,0]·[10,20]=3×10+0×20=30.'),
choice('Médio · Que shape resulta de (4×3)@(3×2)?',['4×2','3×3','4×3'],0,'As dimensões interiores desaparecem e as exteriores ficam.','3 coincide com 3, por isso o produto existe; a saída tem 4 linhas e 2 colunas.'),
n('Difícil · Para A=[[1,2],[3,4]] e B=[[5,6],[7,8]], qual é C₂₁ em C=AB?',43,'Usa a segunda linha de A e a primeira coluna de B.','[3,4]·[5,7]=3×5+4×7=15+28=43.'),
n('Desafiante · X tem shape 6×3 e W tem shape 3×4. Quantos valores contém XW?',24,'Encontra primeiro a shape da saída.','(6×3)@(3×4) produz 6×4. A matriz resultante contém 6×4=24 valores.')
];
m2.task='Calcula à mão A=[[1,2],[0,1]] vezes B=[[2,0],[3,4]]. Confere depois: AB=[[8,8],[3,4]]. Calcula BA e observa que dá [[2,4],[3,10]]. Escreve as shapes e verifica uma célula de cada produto. Depois executa algebra_linear.py e explica por que X*w e X@w respondem a perguntas diferentes.';
m2.code='import numpy as np\n\nX = np.array([[1., 2.], [3., 0.]])\nw = np.array([10., 20.])\nprevisoes = X @ w + 5\nassert X.shape == (2, 2)\nassert w.shape == (2,)\nassert previsoes.shape == (2,)\nassert np.allclose(previsoes, [55., 35.])\nprint({"shape": X.shape, "previsoes": previsoes.tolist()})';
