import fs from 'node:fs';
import path from 'node:path';
import {courses,sources} from '../content/courses.mjs';
import {lessons} from '../content/lessons.mjs';
import '../content/mathematics.mjs';
import '../content/programming.mjs';
import '../content/intro-ml.mjs';
import '../content/deep-nlp.mjs';
import '../content/applied-project.mjs';
import '../content/bases-complete.mjs';
import '../content/bases-module2.mjs';

const e = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const write=(file,text)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);};
const url=l=>`cadeiras/${l.course}/modulo-${l.module+1}/${l.id.toLowerCase()}.html`;
const byId=id=>lessons.find(l=>l.id===id);
const link=(l,base='')=>`<a class="lesson-link" href="${base}${url(l)}"><span class="lesson-id">${l.id}</span><span>${e(l.title)}</span><span class="arrow" aria-hidden="true">↗</span></a>`;
const refs=c=>c.refs.map(k=>`<li><a href="${sources[k][1]}">${e(sources[k][0])}</a></li>`).join('');
function page(title,body,depth=0,id=''){
 const base='../'.repeat(depth);
 return `<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Preparação para a pós-graduação em IA, com bases de matemática e Python para um programador front-end."><title>${e(title)} · Caderno IA</title><link rel="stylesheet" href="${base}assets/site.css"><script defer src="${base}assets/site.js"></script></head><body data-lesson="${id}"><a class="skip" href="#conteudo">Saltar para o conteúdo</a><header class="top"><a class="brand" href="${base}index.html"><span class="brand-mark" aria-hidden="true">ia.</span>Caderno IA</a><nav aria-label="Principal"><a href="${base}percurso.html">O teu percurso</a><a href="${base}index.html#cadeiras">Cadeiras</a><a href="${base}sobre.html">Sobre</a></nav></header><main id="conteudo">${body}</main><footer><span>Aprender, experimentar, compreender.</span><a href="${base}sobre.html">Preparação independente · PT-PT</a></footer></body></html>`;
}
const weeks=[
 ['07–13 set.','Recuperar confiança',['B01','B02','B03','B04'],'3 h de aulas e exercícios + 1 h para repetir contas sem notas.'],
 ['14–20 set.','Pôr Python a funcionar',['B05','B06','P01','I01'],'3 h de aulas + 1 h de instalação, diagnóstico e repetição. Se o diagnóstico falhar, usa essa hora para rever as bases.'],
 ['21–27 set.','Pensar com vetores',['M01','M02','P02'],'2 h 15 de aulas + 1 h 45 para calcular matrizes e executar NumPy.'],
 ['28 set.–04 out.','Dados e incerteza',['M03','P03','P04','I02'],'3 h de aulas + 1 h para desenhar uma divisão de dados e rever denominadores.'],
 ['05–11 out.','Prever e avaliar',['ML01','ML02','ML03'],'2 h 15 de aulas + 1 h 45 para comparar referências e rever erros.'],
 ['12–18 out.','Perceber como aprende',['M04','D01','D02'],'2 h 15 de aulas + 1 h 45 para refazer gradientes à mão.'],
 ['19–25 out.','Um primeiro projeto de texto',['N01','N02','F01','F02'],'3 h de aulas + 1 h para executar o laboratório e documentar os dados.'],
 ['26 out.–01 nov.','Consolidar e explicar',['F03','F04'],'1 h 30 de aulas + 2 h 30 para rever o laboratório, corrigir lacunas e ensaiar uma apresentação.']
];
const cards=courses.map(c=>`<a class="course-card ${c.color}" href="cadeiras/${c.id}/index.html"><div class="card-top"><span>${c.code} / ${c.ects?c.ects+' ECTS':'Preparação'}</span><span aria-hidden="true">↗</span></div><h3>${e(c.title)}</h3><p>${e(c.goal)}</p><span class="card-meta">${c.modules.length} módulos · ${lessons.filter(l=>l.course===c.id).length} aulas</span></a>`).join('');
write('index.html',page('Começar',`<section class="opening"><div><p class="eyebrow">O TEU PERCURSO / SETEMBRO → NOVEMBRO 2026</p><h1>De front-end<br>aos fundamentos de <em>IA.</em></h1><p class="lead">Um caderno de estudo para chegares à pós-graduação com bases. Quatro horas por semana, uma ideia de cada vez.</p><a class="button" href="${url(byId('B01'))}">Começar pela primeira aula <span aria-hidden="true">→</span></a><a class="text-link" href="percurso.html">Ver o plano de 8 semanas</a></div><aside class="start-panel"><span class="eyebrow">PRÓXIMA SESSÃO</span><h2>Primeiro, as bases.</h2><p>Frações, percentagens e sinais. Vais usá-los para compreender taxas de conversão e erros de previsão.</p><div class="session"><span>01</span><div><strong>60 minutos</strong><br>Leitura + prática no papel</div></div><a id="resume" href="${url(byId('B01'))}">Abrir aula B01 ↗</a></aside></section><div class="facts"><span><strong>8</strong> cadeiras + ponte de bases</span><span><strong>38</strong> aulas independentes</span><span><strong>4 h</strong> por semana</span></div><section id="cadeiras"><div class="section-heading"><div><p class="eyebrow">MAPA DE ESTUDO</p><h2>As cadeiras, pela ordem de preparação.</h2></div><p>Começa na ponte de bases.<br>Avança pelos pré-requisitos.</p></div><div class="course-grid">${cards}</div></section><section class="note"><h2>Preparar não é dominar tudo antes de começar.</h2><p>O plano inicial de 32 horas seleciona as bases e um primeiro projeto. O aprofundamento dos módulos de bases requer mais tempo: segue o ritmo atualizado no percurso. As outras aulas e os planos de aprofundamento acompanham-te durante o curso.</p><p>O ISLA publica início previsto em <strong>2 de outubro de 2026</strong>. Mantemos novembro como a tua meta e incluímos um percurso prioritário para outubro. <a href="sobre.html">Ver fontes e limites do plano</a>.</p></section>`));

write('percurso.html',page('O teu percurso',`<div class="page-heading"><p class="eyebrow">PLANO PESSOAL / 32 HORAS</p><h1>Quatro horas.<br>Todas as semanas.</h1><p class="lead">Oito semanas a partir de 7 de setembro. Se começares depois, desloca as sessões; não comprimas duas semanas numa noite.</p></div><section class="note"><h2>Como distribuir as 4 horas</h2><p><strong>Atualização dos módulos de bases:</strong> cada aula marcada como completa exige duas sessões de 60 minutos cada, mais prática e revisão. Reserva uma semana por aula. Desloca o calendário abaixo; não acumules a carga nova com as quatro aulas introdutórias da primeira semana.</p><p>Duas sessões de 1 hora para ideias novas e uma de 2 horas para exercícios e código. A estimativa por aula é de 45 minutos com prática; quando uma base precisar de mais tempo, substitui a próxima aula por revisão.</p><p>Avança quando conseguires resolver pelo menos dois dos três exercícios sem pistas e explicar a conta. Revê os erros 48 horas depois. Na primeira semana, faz um registo em papel das bases em falta.</p></section><div class="weeks">${weeks.map((w,i)=>`<section class="week"><div><p class="eyebrow">SEMANA ${i+1} · ${w[0]}</p><h2>${w[1]}</h2><p>${w[3]}</p></div><div>${w[2].map(id=>link(byId(id))).join('')}</div></section>`).join('')}</div><section class="note"><h2>Se o curso começar a 2 de outubro</h2><p>Tens aproximadamente 14 horas até essa data. Prioriza B01, B02, B03, B04, B05, P01, I01, M01, M02, P04, ML01 e ML02: cerca de 9 horas de aulas e 5 de prática. Retoma o restante plano enquanto frequentas as primeiras aulas.</p><p>Não precisas de terminar Deep Learning ou NLP antes de entrar. Anota os conceitos desconhecidos e usa os pré-requisitos como mapa de revisão.</p></section><section><h2>Depois de novembro</h2><p>Completa I03–I04, ML04, D03–D04, N03–N04 e A01–A04. Reserva 4 horas para as duas primeiras, 4 para ML04 e revisão, 6 para redes, 6 para NLP e 8 para aplicações. São estimativas de estudo, independentes dos ECTS. Ajusta a ordem aos programas entregues pelos docentes.</p><a class="button secondary" href="index.html#cadeiras">Escolher uma cadeira</a></section>`));

write('sobre.html',page('Fontes e método',`<div class="page-heading"><p class="eyebrow">CONTEXTO E TRANSPARÊNCIA</p><h1>Um professor de apoio.<br>Um plano teu.</h1><p class="lead">Conteúdo original de preparação para um programador front-end com pouca experiência em IA e matemática universitária.</p></div><section class="prose"><h2>O que foi confirmado</h2><p>A <a href="${sources.isla[1]}">página do ISLA Gaia</a>, consultada a 7 de setembro de 2026, lista oito unidades curriculares, 30 ECTS e 150 horas de contacto. Identifica o plano como 2025–26 e apresenta início previsto a 2 de outubro de 2026. Confirma com a instituição a data da tua edição.</p><h2>O que é uma proposta pedagógica</h2><p>A página consultada não inclui programas detalhados por cadeira. A divisão em módulos, aulas, projetos, pré-requisitos, carga de preparação e grelhas é uma proposta independente. Não é material oficial, nem uma garantia de aprovação. Os ECTS são os publicados; as horas deste percurso são estimativas próprias.</p><p>As 38 aulas são uma introdução utilizável. Cada SPEC_PLAN distingue essas aulas do aprofundamento planeado para a cadeira. Os conteúdos avançados listados não estão apresentados como aulas já escritas.</p><h2>Referência e fontes</h2><p>A estrutura pedagógica inspira-se no <a href="https://github.com/andrefernandes-95/matematica">teu repositório de matemática</a>: linguagem simples, exemplos guiados e prática. Aqui cada aula tem o seu HTML. Os exemplos de front-end e suporte e as explicações são originais. A documentação abaixo serve para consulta técnica complementar.</p><ul>${Object.values(sources).map(s=>`<li><a href="${s[1]}">${e(s[0])}</a></li>`).join('')}</ul><h2>Como usar os exercícios</h2><p>Tenta primeiro. Usa a pista se necessário e compara o raciocínio com a resolução. A validação numérica aceita vírgula ou ponto, com tolerância de 0,01. As perguntas de escolha mostram a resolução depois da tentativa. O botão de conclusão é uma autoavaliação.</p><h2>Progresso e privacidade</h2><p>O progresso fica apenas neste navegador através de localStorage; não há conta nem sincronização. Podes exportar uma cópia e importar noutro navegador. Não são recolhidos dados por este site. As ligações externas têm as políticas dos respetivos serviços.</p><div class="progress-tools"><button id="export-progress">Exportar progresso</button><label class="file-label">Importar progresso<input id="import-progress" type="file" accept="application/json"></label><button id="reset-progress">Limpar progresso</button></div><p id="storage-status" role="status"></p><h2>Planos e código</h2><p><a href="SPEC_PLAN.md">SPEC_PLAN geral</a> · <a href="README.md">README</a>. Para alterar conteúdos, edita content/ e executa npm run build. Não precisas de um framework no navegador.</p></section>`));

const widget=l=>l.id==='M04'?`<section class="lab-widget"><p class="eyebrow">EXPERIMENTA</p><h2>Um passo sobre a curva de erro</h2><p>L(w) = (w − 3)². Altera o peso inicial e a taxa; observa se a perda diminui.</p><label for="weight">Peso inicial w <output id="weight-value">0</output></label><input id="weight" type="range" min="-2" max="8" value="0" step="0.1"><label for="rate">Taxa de aprendizagem α <output id="rate-value">0,1</output></label><input id="rate" type="range" min="0" max="1.5" value="0.1" step="0.05"><svg viewBox="0 0 500 180" role="img" aria-label="Curva da perda, com posição inicial e posição após um passo"><path d="M20 155 H480 M250 10 V155" stroke="currentColor" fill="none" opacity=".2"/><polyline id="loss-curve" fill="none" stroke="#4265d6" stroke-width="3"/><circle id="before-point" r="6" fill="#4265d6"/><circle id="after-point" r="6" fill="#277249"/></svg><p id="gradient-result" role="status"></p><p class="small">Azul: início. Verde: após o passo. Escala horizontal −7 a 13; vertical 0 a 100.</p></section>`:'';

for(const c of courses){
 const ls=lessons.filter(l=>l.course===c.id);
 write(`cadeiras/${c.id}/index.html`,page(c.title,`<p class="breadcrumb"><a href="../../index.html#cadeiras">Cadeiras</a> / ${c.code}</p><div class="page-heading"><p class="eyebrow">${c.ects?c.ects+' ECTS · PLANO PUBLICADO':'PONTE DE PREPARAÇÃO'} / ${ls.length} AULAS INTRODUTÓRIAS</p><h1>${e(c.title)}</h1><p class="lead">${e(c.goal)}</p></div><div class="course-overview"><section><h2>Antes de começar</h2><p>${e(c.prereq)}</p></section><section><h2>No fim deste percurso</h2><p>${e(c.outcome)}</p></section></div>${c.modules.map((m,i)=>`<section class="module"><p class="eyebrow">MÓDULO ${i+1}</p><h2><a href="modulo-${i+1}/index.html">${e(m)}</a></h2>${ls.filter(l=>l.module===i).map(l=>link(l,'../../')).join('')}</section>`).join('')}<section class="note"><h2>Projeto da cadeira</h2><p>${e(c.project)}</p><p><strong>Como avaliar:</strong> ${e(c.rubric)}</p></section><section><h2>Aprofundamento planeado</h2><p>Estes temas estão especificados para estudo durante a pós-graduação. Ainda não são aulas HTML completas neste repositório.</p><ul>${c.later.map(t=>`<li>${e(t)}</li>`).join('')}</ul><a class="button secondary" href="SPEC_PLAN.md">Ler o SPEC_PLAN desta cadeira ↗</a></section>`,2));
 c.modules.forEach((m,i)=>write(`cadeiras/${c.id}/modulo-${i+1}/index.html`,page(m,`<p class="breadcrumb"><a href="../index.html">${e(c.title)}</a> / Módulo ${i+1}</p><div class="page-heading"><p class="eyebrow">MÓDULO ${i+1}</p><h1>${e(m)}</h1><p class="lead">Estuda as aulas pela ordem indicada. Lê os exemplos, tenta os exercícios e regista o que precisas de rever.</p></div>${c.id==='bases' && i===0 ? '<section class="note"><h2>Módulo completo: duas aulas, passo a passo</h2><p>B01 e B02 incluem desenvolvimento completo e sete exercícios cada. Reserva uma semana de 4 horas por aula, com prática e revisão. Avança depois de resolver 6/7 sem pistas e explicar os passos.</p><a href="SPEC_PLAN.md">Especificação e critérios do módulo</a></section>' : ''}${ls.filter(l=>l.module===i).map(l=>link(l,'../../../')).join('')}`,3)));
 for(let i=0;i<ls.length;i++){
  const l=ls[i];
  const pre=e(l.prereq).replace(/\b(B|M|P|I|ML|D|N|A|F)\d{2}\b/g,id=>byId(id)?`<a href="../../../${url(byId(id))}">${id}</a>`:id);
  const exercises=l.questions.map((q,j)=>`<form class="exercise" data-answer="${q.a}" data-kind="${q.options?'choice':'number'}"><p class="eyebrow">${String(j+1).padStart(2,'0')} / PRÁTICA</p><h3>${e(q.q)}</h3>${q.options?`<fieldset><legend class="sr-only">Escolhe uma resposta</legend>${q.options.map((o,k)=>`<label class="option"><input type="radio" name="answer" value="${k}" required> ${e(o)}</label>`).join('')}</fieldset>`:`<label for="answer-${j}">A tua resposta</label><input id="answer-${j}" name="answer" inputmode="decimal" autocomplete="off" placeholder="Escreve um número" required>`}<button type="submit">Verificar</button><p class="feedback" role="status"></p><details><summary>Preciso de uma pista</summary><p>${e(q.h)}</p></details><details class="solution"><summary>Ver resolução</summary><p>${e(q.s)}</p></details></form>`).join('');
  const labLinks={N02:'suporte.py',D03:'rede.py',P01:'bases.py',F03:'suporte.py'};
  write(url(l),page(l.title,`<p class="breadcrumb"><a href="../index.html">${e(c.title)}</a> / <a href="index.html">Módulo ${l.module+1}</a> / ${l.id}</p><div class="lesson-layout"><aside class="lesson-nav"><p class="eyebrow">NESTA CADEIRA</p>${ls.map(x=>`<a ${x.id===l.id?'aria-current="page"':''} href="../../../${url(x)}"><span>${x.id}</span> ${e(x.title)}</a>`).join('')}<a class="back-plan" href="../../../percurso.html">← Plano semanal</a></aside><article class="prose lesson"><header class="lesson-heading"><p class="eyebrow">AULA ${l.id} · ${l.duration || '45 MINUTOS COM PRÁTICA'}</p><h1>${e(l.title)}</h1><p class="lead">${e(l.goal)}</p><p class="prereq"><strong>Pré-requisitos:</strong> ${pre}</p></header><section><h2>Primeiro, a ideia</h2>${l.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}<div class="formula">${e(l.formula)}</div></section>${l.extra || ''}${widget(l)}<section><p class="eyebrow">EXEMPLO RESOLVIDO A</p><h2>${e(l.exampleA[0])}</h2><p>${e(l.exampleA[1])}</p></section><section><p class="eyebrow">EXEMPLO RESOLVIDO B</p><h2>${e(l.exampleB[0])}</h2><p>${e(l.exampleB[1])}</p></section><aside class="pitfall"><strong>Um erro a evitar</strong><p>${e(l.error)}</p></aside><section><h2>Da ideia ao código</h2><p class="small">${l.code.includes('const ')||l.code.startsWith('//')?'JavaScript · consola do navegador':'Python · executa num ficheiro .py; blocos comentados são esquemas e estão identificados como tal.'}</p><pre><code>${e(l.code)}</code></pre>${labLinks[l.id]?`<p><a href="../../../labs/${labLinks[l.id]}">Abrir laboratório completo: ${labLinks[l.id]}</a> · <a href="../../../labs/README.md">Instruções de execução</a></p>`:''}</section><section id="exercicios"><h2>Agora, tenta tu.</h2><p>Resolve antes de abrir a resposta. Se usares uma pista, volta a tentar sem ela na próxima sessão.</p>${exercises}</section><section class="note"><h2>Aplicar e explicar</h2><p>${e(l.task)}</p><p>Antes de avançar, explica a ideia principal em duas frases e ${l.complete ? 'resolve pelo menos seis dos sete exercícios sem pistas e revê os erros após 48 horas.' : 'resolve pelo menos dois exercícios sem pistas.'}</p></section><section><h2>Consulta complementar</h2><ul>${refs(c)}</ul></section><div class="completion"><button class="complete" data-id="${l.id}">Marcar aula como estudada</button><p class="small completion-state" role="status">Marca pessoal guardada apenas neste navegador.</p></div><nav class="lesson-pagination" aria-label="Navegação entre aulas">${i>0?`<a href="../../../${url(ls[i-1])}">← ${ls[i-1].id}: ${e(ls[i-1].title)}</a>`:'<a href="../index.html">← Cadeira</a>'}${i<ls.length-1?`<a href="../../../${url(ls[i+1])}">${ls[i+1].id}: ${e(ls[i+1].title)} →</a>`:'<a href="../../../percurso.html">Voltar ao percurso →</a>'}</nav></article></div>`,3,l.id));
 }
 write(`cadeiras/${c.id}/SPEC_PLAN.md`,`# SPEC_PLAN — ${c.title}\n\n## Estatuto e perfil\n${c.ects?`${c.ects} ECTS publicados pelo ISLA.`:'Módulo adicional de preparação, sem ECTS.'} Plano pedagógico independente para um programador front-end, bases do secundário frágeis e sem experiência universitária em IA. Não é o programa oficial detalhado. Consulta da fonte: 07-09-2026.\n\n## Objetivo\n${c.goal}\n\n## Pré-requisitos\n${c.prereq}\n\n## Resultado observável\n${c.outcome}\n\n${c.id==='bases'?'## Módulo em aprofundamento\n[Especificação detalhada do módulo 1](modulo-1/SPEC_PLAN.md) e [módulo 2](modulo-2/SPEC_PLAN.md). As aulas seguem o estado registado nesses documentos; duração e avaliação próprias substituem a estimativa introdutória.\n\n':''}## Aulas introdutórias implementadas\nEstimativa de 45 minutos por aula, incluindo exemplos e exercícios. Acrescentar prática e revisão conforme as dificuldades.\n\n${c.modules.map((m,i)=>`### Módulo ${i+1} — ${m}\n${ls.filter(l=>l.module===i).map(l=>`- [${l.id} — ${l.title}](modulo-${i+1}/${l.id.toLowerCase()}.html): ${l.goal} Pré-requisitos: ${l.prereq}`).join('\n')}`).join('\n\n')}\n\n## Aprofundamento planeado — ainda por desenvolver em HTML\n${c.later.map((t,i)=>`### AP${i+1} — ${t}\n- Preparar 2–3 aulas de 60 minutos, começando pelos pré-requisitos das aulas introdutórias.\n- Explicar conceitos e notação, resolver um exemplo numérico mínimo e uma aplicação a dados de suporte ou interfaces.\n- Laboratório: comparar a técnica com o método introdutório correspondente e registar pressupostos e limitações.\n- Aceitação: explicar a técnica, executar um exemplo reproduzível e justificar quando a escolha é inadequada.\n- Validar âmbito contra a ficha da unidade curricular quando disponibilizada pelo docente.\n`).join('\n')}\n## Projeto\n${c.project}\n\n## Avaliação proposta\n${c.rubric}\n\n## Adaptação a 4 horas semanais\nSeguir a seleção em [percurso](../../percurso.html). Não converter ECTS em horas de preparação nem tentar completar o aprofundamento antes de novembro. Quando falhar 2 exercícios, rever o pré-requisito em vez de acelerar.\n\n## Contrato pedagógico de cada aula\nObjetivo concreto; pré-requisitos ligados; intuição antes da fórmula; símbolos explicados; dois exemplos resolvidos; erro frequente; código; três exercícios com pista, validação e resolução; tarefa de transferência. Os exemplos numéricos são deliberadamente pequenos.\n\n## Critérios de entrega\nHTML próprio por aula; navegação módulo/cadeira; sem carregar conteúdos das outras aulas; legibilidade móvel; teclado; links relativos; cálculos revistos; exemplos executáveis ou explicitamente identificados como esquema; sem prometer resultados académicos.\n\n## Fontes\n- [ISLA Gaia](${sources.isla[1]})\n${c.refs.map(k=>`- [${sources[k][0]}](${sources[k][1]})`).join('\n')}\n`);
}
write('assets/catalog.json',JSON.stringify(lessons.map(l=>({id:l.id,title:l.title,url:url(l)}))));
write('manifest.json',JSON.stringify({lessons:lessons.map(l=>({id:l.id,url:url(l),course:l.course})),courses:courses.map(c=>c.id)},null,2));
console.log(`Geradas ${lessons.length} aulas, ${courses.length} planos e ${courses.reduce((s,c)=>s+c.modules.length,0)} páginas de módulo.`);
