import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {lessons} from '../content/lessons.mjs';
import '../content/bases-module3.mjs';
const b5=lessons.find(l=>l.id==='B05');
assert.deepEqual(b5.questions.map(q=>q.a),[0,3,(100+110+390)/3,1,1,1,0]);
assert(b5.extra.includes('./.venv/Scripts/python.exe'));
assert(!b5.extra.includes('.venvScriptspython'));
const b6=lessons.find(l=>l.id==='B06');
const variance=xs=>{const mean=xs.reduce((s,x)=>s+x,0)/xs.length;return xs.reduce((s,x)=>s+(x-mean)**2,0)/xs.length;};
assert.deepEqual(b6.questions.map(q=>q.a),[1/3+1/6,12/80*100,(19-4)/(-3),4*3-2,(4+8)/2,variance([0,2,4,6]),1]);
assert.equal(-3*b6.questions[2].a+4,19);
assert.equal(45+45+90+60,4*60);
assert.equal(1/4+1/8,.375);
assert.equal(9/60*100,15);
assert.equal(-2*(-6)+3,15);
assert(Math.abs(variance([1,3,5])-2.67)<.01);
assert(b6.afterExercises.includes('Segunda tentativa'));
vm.runInNewContext(b6.code,{console:{log(){}}});
const selected=lessons.filter(l=>['B05','B06'].includes(l.id)&&l.complete);
const forms=selected.flatMap(l=>l.questions.map(q=>({dataset:{answer:String(q.a),kind:q.options?'choice':'number'},raw:String(q.a).replace('.',','),feedback:{},solution:{},addEventListener(t,fn){this.submit=fn;},querySelector(s){return s==='.feedback'?this.feedback:this.solution;}})));
vm.runInNewContext(fs.readFileSync('assets/site.js','utf8'),{document:{body:{dataset:{}},getElementById:()=>null,querySelectorAll:()=>forms,querySelector:()=>null},localStorage:{getItem:()=>null},FormData:class{constructor(f){this.f=f;}get(){return this.f.raw;}}});
for(const form of forms){form.submit({preventDefault(){}});assert(form.feedback.textContent.startsWith('Correto'));form.raw=String(Number(form.dataset.answer)+10);form.submit({preventDefault(){}});assert(form.feedback.textContent.startsWith('Ainda'));form.raw='';form.submit({preventDefault(){}});assert(form.feedback.textContent.startsWith('Introduz'));}
console.log(`Módulo 3: ${selected.length} aula(s) e ${forms.length} exercícios validados.`);
